/* Munich place data — fact-checked web research; photos found via web search (49 real, 6 type-default, 0 none). Rebuilt by build-data.js. */
window.MUNICH_DATA = {
  "city": "Munich, Germany",
  "center": {
    "lat": 48.1374,
    "lng": 11.5755
  },
  "categories": [
    {
      "key": "monument",
      "label": "monuments, landmarks & historic sites",
      "food": false
    },
    {
      "key": "restaurant",
      "label": "restaurants & beer gardens",
      "food": true
    },
    {
      "key": "bakery",
      "label": "bakeries, konditoreien & cafes",
      "food": true
    },
    {
      "key": "active",
      "label": "active attractions & outdoor activities",
      "food": false
    },
    {
      "key": "supermarket",
      "label": "supermarkets & grocery stores",
      "food": false
    },
    {
      "key": "pharmacy",
      "label": "pharmacies (Apotheken)",
      "food": false
    }
  ],
  "places": [
    {
      "id": "monument-marienplatz",
      "category": "monument",
      "name": "Marienplatz",
      "rating": 4.7,
      "ratingCount": 95000,
      "address": "Marienplatz 1, 80331 München",
      "lat": 48.137154,
      "lng": 11.575382,
      "neighborhood": "Altstadt-Lehel (Old Town)",
      "description": "Munich's lively central square and the heart of the old town, where families gather to watch the famous Glockenspiel chime from the New Town Hall tower. There's plenty of open space, street performers and ice cream nearby, making it a perfect first stop for kids.",
      "imageUrl": "assets/places/monument-marienplatz.png",
      "isPhoto": true
    },
    {
      "id": "monument-frauenkirche-cathedral-of-our-dear-lady",
      "category": "monument",
      "name": "Frauenkirche (Cathedral of Our Dear Lady)",
      "rating": 4.6,
      "ratingCount": 22000,
      "address": "Frauenplatz 12, 80331 München",
      "lat": 48.138658,
      "lng": 11.573953,
      "neighborhood": "Altstadt-Lehel (Old Town)",
      "description": "This grand Gothic cathedral with its twin onion-domed towers is the unmistakable symbol of Munich's skyline. Step inside to spot the legendary 'Devil's Footprint' on the floor, a fun little mystery that delights curious kids.",
      "imageUrl": "assets/places/monument-frauenkirche-cathedral-of-our-dear-lady.png",
      "isPhoto": true
    },
    {
      "id": "monument-nymphenburg-palace-schloss-nymphenburg",
      "category": "monument",
      "name": "Nymphenburg Palace (Schloss Nymphenburg)",
      "rating": 4.6,
      "ratingCount": 35000,
      "address": "Schloss Nymphenburg 1, 80638 München",
      "lat": 48.158303,
      "lng": 11.503352,
      "neighborhood": "Neuhausen-Nymphenburg",
      "description": "A magnificent Baroque summer palace surrounded by sprawling gardens, canals and fountains where families can stroll, picnic and watch swans glide by. The lavish royal rooms and the whimsical 'Beauty Gallery' make it a storybook day out.",
      "imageUrl": "assets/places/monument-nymphenburg-palace-schloss-nymphenburg.png",
      "isPhoto": true
    },
    {
      "id": "monument-munich-residenz",
      "category": "monument",
      "name": "Munich Residenz",
      "rating": 4.7,
      "ratingCount": 30000,
      "address": "Residenzstraße 1, 80333 München",
      "lat": 48.141329,
      "lng": 11.578289,
      "neighborhood": "Altstadt-Lehel (Old Town)",
      "description": "Once the royal palace of Bavaria's kings, this enormous complex dazzles with opulent halls, courtyards and a sparkling treasury full of crowns and jewels. Kids love hunting for the gilded grotto and the glittering gemstones on the family-friendly audio tour.",
      "imageUrl": "assets/places/monument-munich-residenz.png",
      "isPhoto": true
    },
    {
      "id": "monument-siegestor-victory-gate",
      "category": "monument",
      "name": "Siegestor (Victory Gate)",
      "rating": 4.6,
      "ratingCount": 6500,
      "address": "Leopoldstraße 1, 80539 München",
      "lat": 48.151667,
      "lng": 11.581389,
      "neighborhood": "Maxvorstadt / Schwabing",
      "description": "A grand triumphal arch crowned by a lion-drawn chariot, often compared to the Arc de Triomphe in Paris. It marks the lively gateway to the student district of Schwabing and is a striking, free photo stop for the whole family.",
      "imageUrl": "assets/places/monument-siegestor-victory-gate.png",
      "isPhoto": true
    },
    {
      "id": "monument-asamkirche-st-johann-nepomuk",
      "category": "monument",
      "name": "Asamkirche (St. Johann Nepomuk)",
      "rating": 4.7,
      "ratingCount": 9000,
      "address": "Sendlinger Straße 32, 80331 München",
      "lat": 48.135222,
      "lng": 11.570722,
      "neighborhood": "Hackenviertel (Old Town)",
      "description": "A tiny but breathtaking Baroque-Rococo church tucked between shops, overflowing with gold, frescoes and dramatic detail on every surface. Its jewel-box interior wows visitors of all ages in just a few awe-filled minutes.",
      "imageUrl": "assets/places/monument-asamkirche-st-johann-nepomuk.png",
      "isPhoto": true
    },
    {
      "id": "monument-odeonsplatz",
      "category": "monument",
      "name": "Odeonsplatz",
      "rating": 4.6,
      "ratingCount": 11000,
      "address": "Odeonsplatz, 80539 München",
      "lat": 48.142222,
      "lng": 11.5775,
      "neighborhood": "Altstadt-Lehel (Old Town)",
      "description": "An elegant Italian-inspired square framed by the bright-yellow Theatine Church and the grand Feldherrnhalle loggia. It's a wide, open space great for family photos and a relaxed start to a walk up the stately Ludwigstraße.",
      "imageUrl": "assets/places/monument-odeonsplatz.png",
      "isPhoto": true
    },
    {
      "id": "monument-st-peter-s-church-alter-peter",
      "category": "monument",
      "name": "St. Peter's Church (Alter Peter)",
      "rating": 4.7,
      "ratingCount": 18000,
      "address": "Rindermarkt 1, 80331 München",
      "lat": 48.136469,
      "lng": 11.575941,
      "neighborhood": "Altstadt-Lehel (Old Town)",
      "description": "Munich's oldest parish church, whose 91-metre tower 'Alter Peter' rewards those who climb its roughly 300 steps with sweeping views of the old town and, on clear days, the Alps. A fun little adventure for energetic kids right beside Marienplatz.",
      "imageUrl": "assets/places/monument-st-peter-s-church-alter-peter.png",
      "isPhoto": true
    },
    {
      "id": "monument-sendlinger-tor",
      "category": "monument",
      "name": "Sendlinger Tor",
      "rating": 4.5,
      "ratingCount": 6000,
      "address": "Sendlinger-Tor-Platz 1, 80336 München",
      "lat": 48.133611,
      "lng": 11.567222,
      "neighborhood": "Hackenviertel / Isarvorstadt",
      "description": "One of Munich's three surviving medieval city gates, beautifully restored with twin Gothic towers marking the southern edge of the old town. It's a great free landmark to walk through on the way to the shops and Christmas market on Sendlinger Straße.",
      "imageUrl": "assets/places/monument-sendlinger-tor.png",
      "isPhoto": true
    },
    {
      "id": "monument-chinesischer-turm-chinese-tower-englischer-garten",
      "category": "monument",
      "name": "Chinesischer Turm (Chinese Tower), Englischer Garten",
      "rating": 4.5,
      "ratingCount": 13000,
      "address": "Englischer Garten 3, 80538 München",
      "lat": 48.151931,
      "lng": 11.592235,
      "neighborhood": "Englischer Garten (Schwabing-Freimann)",
      "description": "A charming wooden pagoda-style tower at the heart of the vast English Garden, surrounded by one of Munich's largest and most relaxed beer gardens. Families can spread out on the lawns, enjoy Bavarian snacks and let the kids run free in the huge park.",
      "imageUrl": "assets/places/monument-chinesischer-turm-chinese-tower-englischer-garten.png",
      "isPhoto": true
    },
    {
      "id": "restaurant-hofbrauhaus-munchen",
      "category": "restaurant",
      "name": "Hofbräuhaus München",
      "rating": 4.4,
      "ratingCount": 90000,
      "address": "Platzl 9, 80331 München",
      "lat": 48.1374,
      "lng": 11.5797,
      "neighborhood": "Altstadt-Lehel (Platzl, city center)",
      "description": "Munich's most famous beer hall, founded in 1589, with a lively festive atmosphere, live Bavarian brass music and big plates of pretzels, sausages and roast chicken. The huge communal tables and cheerful buzz make it an easy, memorable stop for families exploring the old town.",
      "imageUrl": "assets/places/restaurant-hofbrauhaus-munchen.png",
      "isPhoto": true
    },
    {
      "id": "restaurant-augustiner-keller",
      "category": "restaurant",
      "name": "Augustiner-Keller",
      "rating": 4.5,
      "ratingCount": 18000,
      "address": "Arnulfstraße 52, 80335 München",
      "lat": 48.1442,
      "lng": 11.5497,
      "neighborhood": "Maxvorstadt (near Hauptbahnhof)",
      "description": "A beloved, leafy beer garden under old chestnut trees serving Augustiner's famous Edelstoff straight from wooden barrels alongside hearty Bavarian classics. With thousands of shaded seats and a relaxed local feel, there's plenty of room for kids to roam while grown-ups enjoy a stein.",
      "imageUrl": "assets/places/restaurant-augustiner-keller.png",
      "isPhoto": true
    },
    {
      "id": "restaurant-wirtshaus-in-der-au",
      "category": "restaurant",
      "name": "Wirtshaus in der Au",
      "rating": 4.5,
      "ratingCount": 6500,
      "address": "Lilienstraße 51, 81669 München",
      "lat": 48.1289,
      "lng": 11.5836,
      "neighborhood": "Au-Haidhausen",
      "description": "A warm, historic Bavarian tavern open since 1901 that is famous for its dumplings, roast duck and organic local fare near the Deutsches Museum. The cozy, welcoming atmosphere and classic comfort food make it a relaxed choice for a family dinner.",
      "imageUrl": "assets/places/restaurant-wirtshaus-in-der-au.png",
      "isPhoto": true
    },
    {
      "id": "restaurant-biergarten-am-chinesischen-turm",
      "category": "restaurant",
      "name": "Biergarten am Chinesischen Turm",
      "rating": 4.3,
      "ratingCount": 14000,
      "address": "Englischer Garten 3, 80538 München",
      "lat": 48.1525,
      "lng": 11.5923,
      "neighborhood": "Schwabing (Englischer Garten)",
      "description": "Munich's second-largest beer garden, set around a charming wooden pagoda in the English Garden with around 7,000 seats shaded by chestnut trees. On weekends a Bavarian band plays from the tower, and there's space for kids to run and a nearby carousel, making it a classic family outing.",
      "imageUrl": "assets/places/restaurant-biergarten-am-chinesischen-turm.png",
      "isPhoto": true
    },
    {
      "id": "restaurant-koniglicher-hirschgarten",
      "category": "restaurant",
      "name": "Königlicher Hirschgarten",
      "rating": 4.4,
      "ratingCount": 9000,
      "address": "Hirschgarten 1, 80639 München",
      "lat": 48.1539,
      "lng": 11.5147,
      "neighborhood": "Neuhausen-Nymphenburg",
      "description": "The largest beer garden in the world with around 8,000 seats under giant chestnut trees, run as a Bavarian restaurant since the late 18th century. Best of all for families, there's an adjoining deer enclosure, playgrounds and a carousel, so children are entertained while parents enjoy Augustiner beer and Wirtshaus classics.",
      "imageUrl": "assets/places/restaurant-koniglicher-hirschgarten.png",
      "isPhoto": true
    },
    {
      "id": "restaurant-seehaus-im-englischen-garten",
      "category": "restaurant",
      "name": "Seehaus im Englischen Garten",
      "rating": 4.3,
      "ratingCount": 9500,
      "address": "Kleinhesselohe 3, 80802 München",
      "lat": 48.1626,
      "lng": 11.5963,
      "neighborhood": "Schwabing (Englischer Garten)",
      "description": "A scenic restaurant and beer garden right on the Kleinhesseloher lake in the English Garden, with terraces overlooking the water and rowboats for hire nearby. Families can grab pretzels, Obatzda and roast pork in the self-service beer garden or enjoy a sit-down meal with a lovely lakeside view.",
      "imageUrl": "assets/places/restaurant-seehaus-im-englischen-garten.png",
      "isPhoto": true
    },
    {
      "id": "restaurant-paulaner-am-nockherberg",
      "category": "restaurant",
      "name": "Paulaner am Nockherberg",
      "rating": 4.2,
      "ratingCount": 8000,
      "address": "Hochstraße 77, 81541 München",
      "lat": 48.1226,
      "lng": 11.5856,
      "neighborhood": "Au-Haidhausen",
      "description": "The flagship Paulaner brewery restaurant and beer garden, famous as the home of Munich's strong-beer festival, with a chestnut-shaded garden seating around 3,000. Big Bavarian portions, a sunny terrace and an easygoing atmosphere make it a comfortable spot for a family meal east of the Isar.",
      "imageUrl": "assets/places/restaurant-paulaner-am-nockherberg.png",
      "isPhoto": true
    },
    {
      "id": "restaurant-augustiner-braustuben",
      "category": "restaurant",
      "name": "Augustiner Bräustuben",
      "rating": 4.5,
      "ratingCount": 8000,
      "address": "Landsberger Straße 19, 80339 München",
      "lat": 48.1391,
      "lng": 11.5409,
      "neighborhood": "Ludwigsvorstadt-Isarvorstadt (Westend)",
      "description": "An authentic, down-to-earth Bavarian beer hall set inside the historic Augustiner brewery, where you can sometimes glimpse the brewery's stately horses. Loved by locals for fresh Augustiner beer and honest, hearty food at fair prices, it offers a genuine Munich experience away from the tourist crowds.",
      "imageUrl": "assets/places/restaurant-augustiner-braustuben.png",
      "isPhoto": true
    },
    {
      "id": "restaurant-l-osteria-munchen-leopoldstrasse",
      "category": "restaurant",
      "name": "L'Osteria München Leopoldstraße",
      "rating": 4.1,
      "ratingCount": 6500,
      "address": "Leopoldstraße 28a, 80802 München",
      "lat": 48.1605,
      "lng": 11.5862,
      "neighborhood": "Schwabing",
      "description": "A lively, relaxed Italian spot on bustling Leopoldstraße famous for its enormous thin-crust pizzas that spill over the plate and are perfect for sharing. The casual atmosphere, fair prices and kid-friendly menu make it a reliable, fun choice for families wanting a break from Bavarian fare.",
      "imageUrl": "assets/defaults/restaurant.png",
      "isPhoto": false
    },
    {
      "id": "bakery-rischart-cafe-am-marienplatz",
      "category": "bakery",
      "name": "Rischart Café am Marienplatz",
      "rating": 4.1,
      "ratingCount": 3500,
      "address": "Marienplatz 18, 80331 München",
      "lat": 48.1369,
      "lng": 11.5755,
      "neighborhood": "Altstadt (Marienplatz)",
      "description": "A beloved five-generation Munich bakery-café right on Marienplatz, with cases full of cakes, tarts and pastries and unbeatable upstairs views of the Glockenspiel that delight kids and grown-ups alike. A perfect coffee-and-cake stop in the heart of the old town.",
      "imageUrl": "assets/places/bakery-rischart-cafe-am-marienplatz.png",
      "isPhoto": true
    },
    {
      "id": "bakery-schmalznudel-cafe-frischhut",
      "category": "bakery",
      "name": "Schmalznudel - Café Frischhut",
      "rating": 4.5,
      "ratingCount": 4000,
      "address": "Prälat-Zistl-Straße 8, 80331 München",
      "lat": 48.1349,
      "lng": 11.5762,
      "neighborhood": "Altstadt (Viktualienmarkt)",
      "description": "A cozy, nostalgic institution near the Viktualienmarkt famous for its freshly fried Schmalznudel and Bavarian Auszogne pastries, served warm with coffee. Kids love watching the dough fried right at the counter (cash only).",
      "imageUrl": "assets/defaults/bakery.png",
      "isPhoto": false
    },
    {
      "id": "bakery-julius-brantner-brothandwerk",
      "category": "bakery",
      "name": "Julius Brantner Brothandwerk",
      "rating": 4.8,
      "ratingCount": 1100,
      "address": "Nordendstraße 23, 80801 München",
      "lat": 48.1612,
      "lng": 11.5772,
      "neighborhood": "Schwabing",
      "description": "Munich's most celebrated artisan baker, where slow-fermented organic sourdough loaves and buttery pastries are baked behind glass in a transparent open bakery. Worth the weekend queue for a warm loaf to share with the family.",
      "imageUrl": "assets/defaults/bakery.png",
      "isPhoto": false
    },
    {
      "id": "bakery-boulangerie-dompierre",
      "category": "bakery",
      "name": "Boulangerie Dompierre",
      "rating": 4.3,
      "ratingCount": 1800,
      "address": "Hans-Sachs-Straße 1, 80469 München",
      "lat": 48.132,
      "lng": 11.5707,
      "neighborhood": "Glockenbachviertel (Isarvorstadt)",
      "description": "Munich's go-to French bakery in the lively Glockenbach quarter, known for crackly baguettes, flaky croissants and irresistible éclairs and apple tarts. A charming, friendly spot for a French-style family treat.",
      "imageUrl": "assets/places/bakery-boulangerie-dompierre.png",
      "isPhoto": true
    },
    {
      "id": "bakery-cafe-luitpold",
      "category": "bakery",
      "name": "Café Luitpold",
      "rating": 3.9,
      "ratingCount": 4600,
      "address": "Brienner Straße 11, 80333 München",
      "lat": 48.143,
      "lng": 11.5743,
      "neighborhood": "Maxvorstadt",
      "description": "A grand, historic Viennese-style coffee house founded in 1888, famed for its house-made pralines, elegant cakes and sunny glasshouse atrium. A lovely place to linger over coffee and a slice of torte with the family.",
      "imageUrl": "assets/places/bakery-cafe-luitpold.png",
      "isPhoto": true
    },
    {
      "id": "bakery-conditorei-cafe-kreutzkamm",
      "category": "bakery",
      "name": "Conditorei Café Kreutzkamm",
      "rating": 4.2,
      "ratingCount": 600,
      "address": "Pacellistraße 5, 80333 München",
      "lat": 48.1394,
      "lng": 11.5718,
      "neighborhood": "Altstadt",
      "description": "A traditional family pastry shop with roots dating to 1825, renowned for its handmade Baumkuchen, Prinzregententorte and classic German cakes just steps from Marienplatz. An old-world coffee-and-cake treat the whole family can enjoy.",
      "imageUrl": "assets/places/bakery-conditorei-cafe-kreutzkamm.png",
      "isPhoto": true
    },
    {
      "id": "bakery-brot-feinbackerei-neulinger",
      "category": "bakery",
      "name": "Brot & Feinbäckerei Neulinger",
      "rating": 4.3,
      "ratingCount": 240,
      "address": "Volkartstraße 48, 80636 München",
      "lat": 48.1547,
      "lng": 11.5413,
      "neighborhood": "Neuhausen-Nymphenburg",
      "description": "A certified-organic neighborhood bakery in Neuhausen where naturally leavened breads are baked in a master baker's own wood-fired oven. A friendly, down-to-earth spot for fresh bread, pretzels and pastries.",
      "imageUrl": "assets/defaults/bakery.png",
      "isPhoto": false
    },
    {
      "id": "bakery-cafe-glockenspiel",
      "category": "bakery",
      "name": "Café Glockenspiel",
      "rating": 4,
      "ratingCount": 900,
      "address": "Marienplatz 28, 80331 München",
      "lat": 48.1372,
      "lng": 11.576,
      "neighborhood": "Altstadt (Marienplatz)",
      "description": "A relaxed top-floor café overlooking Marienplatz, beloved for hearty breakfasts, good coffee and homemade strudel with a front-row view of the Rathaus Glockenspiel. A memorable, family-friendly perch above the bustle.",
      "imageUrl": "assets/places/bakery-cafe-glockenspiel.png",
      "isPhoto": true
    },
    {
      "id": "active-englischer-garten",
      "category": "active",
      "name": "Englischer Garten",
      "rating": 4.7,
      "ratingCount": 95000,
      "address": "Englischer Garten 2, 80538 München",
      "lat": 48.1642,
      "lng": 11.6056,
      "neighborhood": "Schwabing / Lehel",
      "description": "One of the largest urban parks in the world, with endless meadows, shady tree-lined paths, streams, and a beer garden by the Chinese Tower. Perfect for a family stroll, a bike ride, a picnic, or watching the surfers on the Eisbach.",
      "imageUrl": "assets/places/active-englischer-garten.png",
      "isPhoto": true
    },
    {
      "id": "active-eisbachwelle",
      "category": "active",
      "name": "Eisbachwelle",
      "rating": 4.7,
      "ratingCount": 3500,
      "address": "Prinzregentenstraße 1, 80538 München",
      "lat": 48.1437,
      "lng": 11.5887,
      "neighborhood": "Lehel",
      "description": "Munich's famous standing river wave at the southern edge of the English Garden, where wetsuited surfers ride year-round. It's free to watch and an unforgettable, only-in-Munich spectacle for kids and grown-ups alike.",
      "imageUrl": "assets/places/active-eisbachwelle.png",
      "isPhoto": true
    },
    {
      "id": "active-olympiapark-munchen",
      "category": "active",
      "name": "Olympiapark München",
      "rating": 4.6,
      "ratingCount": 60000,
      "address": "Spiridon-Louis-Ring 21, 80809 München",
      "lat": 48.1748,
      "lng": 11.5501,
      "neighborhood": "Milbertshofen-Am Hart / Olympiapark",
      "description": "The sweeping green grounds of the 1972 Olympics, with grassy hills, a lake, playgrounds, and the climbable Olympiaberg for great city views. A wonderful spot for families to walk, cycle, fly kites, or paddle on the lake.",
      "imageUrl": "assets/places/active-olympiapark-munchen.png",
      "isPhoto": true
    },
    {
      "id": "active-boulderwelt-munchen-ost",
      "category": "active",
      "name": "Boulderwelt München Ost",
      "rating": 4.6,
      "ratingCount": 4200,
      "address": "Hanne-Hiob-Straße 4, 81671 München",
      "lat": 48.1235,
      "lng": 11.6082,
      "neighborhood": "Berg am Laim",
      "description": "One of the world's largest bouldering gyms, spanning multiple floors of colorful walls for every level plus a dedicated kids' area. A great rainy-day adventure where the whole family can climb, play, and refuel in the cafe.",
      "imageUrl": "assets/places/active-boulderwelt-munchen-ost.png",
      "isPhoto": true
    },
    {
      "id": "active-flaucher",
      "category": "active",
      "name": "Flaucher",
      "rating": 4.6,
      "ratingCount": 4000,
      "address": "Isarauen 8, 81379 München",
      "lat": 48.1031,
      "lng": 11.5447,
      "neighborhood": "Sendling / Thalkirchen",
      "description": "A beloved stretch of the Isar's wild riverbanks with gravel beaches, shallow water, and forest, ideal for paddling, barbecues, and lazy summer afternoons. There's even a classic beer garden tucked among the trees for families.",
      "imageUrl": "assets/places/active-flaucher.png",
      "isPhoto": true
    },
    {
      "id": "active-westpark",
      "category": "active",
      "name": "Westpark",
      "rating": 4.6,
      "ratingCount": 12379,
      "address": "Pressburger Straße 19, 81373 München",
      "lat": 48.1231,
      "lng": 11.5137,
      "neighborhood": "Sendling-Westpark",
      "description": "A beautifully landscaped park with lakes, an East Asian garden, playgrounds, and miles of walking and cycling paths. In summer there's open-air cinema and two beer gardens, making it a relaxed family favorite.",
      "imageUrl": "assets/places/active-westpark.png",
      "isPhoto": true
    },
    {
      "id": "active-tierpark-hellabrunn",
      "category": "active",
      "name": "Tierpark Hellabrunn",
      "rating": 4.6,
      "ratingCount": 33657,
      "address": "Tierparkstraße 30, 81543 München",
      "lat": 48.0993,
      "lng": 11.5547,
      "neighborhood": "Thalkirchen-Obersendling-Forstenried",
      "description": "Set in the green Isar floodplains, this geo-zoo groups its animals by continent across spacious, natural habitats. With lots of walking, playgrounds, and a petting area, it's a full day of outdoor fun for families.",
      "imageUrl": "assets/places/active-tierpark-hellabrunn.png",
      "isPhoto": true
    },
    {
      "id": "active-dav-kletter-und-boulderzentrum-munchen-sud-thalkirchen",
      "category": "active",
      "name": "DAV Kletter- und Boulderzentrum München-Süd (Thalkirchen)",
      "rating": 4.6,
      "ratingCount": 2500,
      "address": "Thalkirchner Straße 207, 81371 München",
      "lat": 48.1083,
      "lng": 11.5436,
      "neighborhood": "Sendling / Thalkirchen",
      "description": "One of Europe's largest climbing and bouldering centers, with towering indoor walls, a big outdoor area, and gear rental on site. Family and beginner zones make it easy for first-timers and kids to try roped climbing safely.",
      "imageUrl": "assets/places/active-dav-kletter-und-boulderzentrum-munchen-sud-thalkirchen.png",
      "isPhoto": true
    },
    {
      "id": "active-schlosspark-nymphenburg",
      "category": "active",
      "name": "Schlosspark Nymphenburg",
      "rating": 4.7,
      "ratingCount": 50000,
      "address": "Schloß Nymphenburg 1, 80638 München",
      "lat": 48.1583,
      "lng": 11.5033,
      "neighborhood": "Neuhausen-Nymphenburg",
      "description": "The grand baroque palace gardens stretch over 180 hectares of canals, lakes, fountains, and tree-lined avenues that are free to wander. A peaceful, scenic place for long family walks, running, and spotting swans and pavilions.",
      "imageUrl": "assets/places/active-schlosspark-nymphenburg.png",
      "isPhoto": true
    },
    {
      "id": "active-boulderwelt-munchen-west",
      "category": "active",
      "name": "Boulderwelt München West",
      "rating": 4.7,
      "ratingCount": 1700,
      "address": "Bertha-Kipfmüller-Straße 19, 81249 München",
      "lat": 48.1493,
      "lng": 11.4452,
      "neighborhood": "Aubing-Lochhausen-Langwied",
      "description": "A modern, family-friendly bouldering gym with ever-changing routes, an outdoor climbing area, and a relaxed cafe. Often praised as one of the best spots for families to climb together in Munich.",
      "imageUrl": "assets/places/active-boulderwelt-munchen-west.png",
      "isPhoto": true
    },
    {
      "id": "supermarket-edeka-ernst",
      "category": "supermarket",
      "name": "EDEKA Ernst",
      "rating": 4.1,
      "ratingCount": 1700,
      "address": "Arnulfstrasse 2, 80335 Muenchen",
      "lat": 48.1419,
      "lng": 11.5556,
      "neighborhood": "Maxvorstadt",
      "description": "A big, bright supermarket right by the main station with an enormous selection and very long opening hours, making it an easy stop for families running errands at almost any hour. Wide aisles and a great fresh-produce section keep stroller-pushing parents happy.",
      "imageUrl": "assets/places/supermarket-edeka-ernst.png",
      "isPhoto": true
    },
    {
      "id": "supermarket-rewe-center-am-arabellapark",
      "category": "supermarket",
      "name": "REWE Center am Arabellapark",
      "rating": 4.2,
      "ratingCount": 1600,
      "address": "Rosenkavalierplatz 5, 81925 Muenchen",
      "lat": 48.1547,
      "lng": 11.6238,
      "neighborhood": "Bogenhausen (Arabellapark)",
      "description": "One of the largest REWE stores in Munich, spread over two floors with a huge range of fresh, organic and everyday groceries plus plenty of parking. The spacious layout and friendly staff make it a stress-free spot for a full family shop.",
      "imageUrl": "assets/defaults/supermarket.png",
      "isPhoto": false
    },
    {
      "id": "supermarket-rewe-city-fuenf-hoefe",
      "category": "supermarket",
      "name": "REWE City (Fuenf Hoefe)",
      "rating": 4.1,
      "ratingCount": 900,
      "address": "Theatinerstrasse 14, 80333 Muenchen",
      "lat": 48.1404,
      "lng": 11.5739,
      "neighborhood": "Altstadt-Lehel",
      "description": "An award-winning premium supermarket tucked inside the elegant Fuenf Hoefe passage, famous for its outstanding fresh counters, fruit and vegetables. A lovely place to grab high-quality groceries while exploring the old town with the family.",
      "imageUrl": "assets/places/supermarket-rewe-city-fuenf-hoefe.png",
      "isPhoto": true
    },
    {
      "id": "supermarket-edeka-leopoldstrasse",
      "category": "supermarket",
      "name": "EDEKA Leopoldstrasse",
      "rating": 4.2,
      "ratingCount": 1100,
      "address": "Leopoldstrasse 41, 80802 Muenchen",
      "lat": 48.1607,
      "lng": 11.5862,
      "neighborhood": "Schwabing",
      "description": "A clean, well-stocked Edeka in the heart of lively Schwabing, praised for top-quality fruit and vegetables and fair prices. Handy for families combining a stroll along Leopoldstrasse with a quick grocery run.",
      "imageUrl": "assets/places/supermarket-edeka-leopoldstrasse.png",
      "isPhoto": true
    },
    {
      "id": "supermarket-vollcorner-biomarkt-maxvorstadt",
      "category": "supermarket",
      "name": "VollCorner Biomarkt Maxvorstadt",
      "rating": 4.5,
      "ratingCount": 120,
      "address": "Augustenstrasse 55, 80333 Muenchen",
      "lat": 48.1505,
      "lng": 11.5631,
      "neighborhood": "Maxvorstadt",
      "description": "A welcoming neighborhood organic market with excellent fresh produce, a fresh-food counter, regional baked goods and natural cosmetics. Friendly service and high bio quality make it a favorite for health-conscious families.",
      "imageUrl": "assets/places/supermarket-vollcorner-biomarkt-maxvorstadt.png",
      "isPhoto": true
    },
    {
      "id": "supermarket-vollcorner-biomarkt-nymphenburg-gern",
      "category": "supermarket",
      "name": "VollCorner Biomarkt Nymphenburg/Gern",
      "rating": 4.6,
      "ratingCount": 90,
      "address": "Nederlinger Strasse 72, 80638 Muenchen",
      "lat": 48.1672,
      "lng": 11.5189,
      "neighborhood": "Neuhausen-Nymphenburg (Gern)",
      "description": "A lovingly renovated organic store serving the leafy Gern and Nymphenburg neighborhoods since 2009, near Schloss Nymphenburg. Great regional and exotic ingredients make it a relaxed, family-friendly stop after a palace-park outing.",
      "imageUrl": "assets/places/supermarket-vollcorner-biomarkt-nymphenburg-gern.png",
      "isPhoto": true
    },
    {
      "id": "supermarket-tegut-gute-lebensmittel-maxvorstadt-elisenhof",
      "category": "supermarket",
      "name": "tegut... gute Lebensmittel Maxvorstadt (Elisenhof)",
      "rating": 4,
      "ratingCount": 250,
      "address": "Luitpoldstrasse 3, 80335 Muenchen",
      "lat": 48.1437,
      "lng": 11.5631,
      "neighborhood": "Maxvorstadt (Klinikviertel)",
      "description": "A spacious tegut in the Elisenhof center near the main station, with a large bio range and a good fresh fruit-and-vegetable selection. Central and easy to reach, it is a convenient choice for families shopping downtown.",
      "imageUrl": "assets/places/supermarket-tegut-gute-lebensmittel-maxvorstadt-elisenhof.png",
      "isPhoto": true
    },
    {
      "id": "supermarket-tegut-gute-lebensmittel-glockenbachviertel",
      "category": "supermarket",
      "name": "tegut... gute Lebensmittel Glockenbachviertel",
      "rating": 4,
      "ratingCount": 150,
      "address": "Muellerstrasse 45, 80469 Muenchen",
      "lat": 48.1322,
      "lng": 11.5708,
      "neighborhood": "Glockenbachviertel (Isarvorstadt)",
      "description": "A friendly tegut in the trendy Glockenbachviertel with a fresh-service counter and a strong organic selection. Perfect for families living or visiting in this central, walkable neighborhood.",
      "imageUrl": "assets/places/supermarket-tegut-gute-lebensmittel-glockenbachviertel.png",
      "isPhoto": true
    },
    {
      "id": "supermarket-tegut-gute-lebensmittel-neuperlach-perlach-plaza",
      "category": "supermarket",
      "name": "tegut... gute Lebensmittel Neuperlach (Perlach Plaza)",
      "rating": 4.3,
      "ratingCount": 300,
      "address": "Theodor-Heuss-Platz 5, 81737 Muenchen",
      "lat": 48.1006,
      "lng": 11.6447,
      "neighborhood": "Neuperlach (Ramersdorf-Perlach)",
      "description": "A modern supermarket in the basement of Perlach Plaza directly connected to the U-Bahn, with wide aisles, fresh produce and an open fresh counter. Praised as the best market in the area, it is an easy and pleasant family shop.",
      "imageUrl": "assets/places/supermarket-tegut-gute-lebensmittel-neuperlach-perlach-plaza.png",
      "isPhoto": true
    },
    {
      "id": "pharmacy-internationale-ludwigs-apotheke",
      "category": "pharmacy",
      "name": "Internationale Ludwigs-Apotheke",
      "rating": 4.1,
      "ratingCount": 188,
      "address": "Neuhauser Str. 11, 80331 Muenchen",
      "lat": 48.1378,
      "lng": 11.5705,
      "neighborhood": "Altstadt (Old Town)",
      "description": "A historic family-run pharmacy (since 1827) right in the pedestrian zone between Marienplatz and Stachus, with over 15,000 products in stock and multilingual staff who can advise the whole family in English, Russian, Arabic and more. Great for travellers needing hard-to-find international medications.",
      "imageUrl": "assets/places/pharmacy-internationale-ludwigs-apotheke.png",
      "isPhoto": true
    },
    {
      "id": "pharmacy-rathaus-apotheke-am-marienplatz",
      "category": "pharmacy",
      "name": "Rathaus-Apotheke am Marienplatz",
      "rating": 4,
      "ratingCount": 90,
      "address": "Marienplatz 8, 80331 Muenchen",
      "lat": 48.1373,
      "lng": 11.5755,
      "neighborhood": "Altstadt (Angerviertel)",
      "description": "A friendly, certified pharmacy directly on Marienplatz with English-speaking staff and quick, competent service, perfect for families exploring the city centre who need a quick remedy. Conveniently central and easy to reach by U-Bahn or S-Bahn.",
      "imageUrl": "assets/places/pharmacy-rathaus-apotheke-am-marienplatz.png",
      "isPhoto": true
    },
    {
      "id": "pharmacy-internationale-hauptbahnhof-apotheke",
      "category": "pharmacy",
      "name": "Internationale Hauptbahnhof Apotheke",
      "rating": 4.8,
      "ratingCount": 22,
      "address": "Bayerstr. 27, 80335 Muenchen",
      "lat": 48.1395,
      "lng": 11.5588,
      "neighborhood": "Ludwigsvorstadt (Hauptbahnhof)",
      "description": "A top-rated pharmacy just steps from Munich's main train station, praised for unhurried, friendly and competent advice and long hours (Mon-Sat until 8pm). A handy stop for arriving or departing families, with a 24-hour pickup machine for pre-ordered medication.",
      "imageUrl": "assets/places/pharmacy-internationale-hauptbahnhof-apotheke.png",
      "isPhoto": true
    },
    {
      "id": "pharmacy-stadtapotheke-am-hauptbahnhof",
      "category": "pharmacy",
      "name": "Stadtapotheke am Hauptbahnhof",
      "rating": 4.5,
      "ratingCount": 70,
      "address": "Goethestr. 8, 80336 Muenchen",
      "lat": 48.1361,
      "lng": 11.5613,
      "neighborhood": "Ludwigsvorstadt-Isarvorstadt",
      "description": "A welcoming neighbourhood pharmacy near the station where owner Malika Rabah and her team advise in English, Arabic and French, making it easy for international families to get the help they need. Open six days a week with friendly, patient service.",
      "imageUrl": "assets/places/pharmacy-stadtapotheke-am-hauptbahnhof.png",
      "isPhoto": true
    },
    {
      "id": "pharmacy-stachus-apotheke",
      "category": "pharmacy",
      "name": "Stachus-Apotheke",
      "rating": 4.2,
      "ratingCount": 60,
      "address": "Karlsplatz 4, 80335 Muenchen",
      "lat": 48.1392,
      "lng": 11.5655,
      "neighborhood": "Altstadt (Karlsplatz/Stachus)",
      "description": "A long-established pharmacy right at the busy Stachus (Karlsplatz), next to the Gloria cinema, well stocked and convenient for families shopping in the centre. Known for careful guidance on complex therapies as well as everyday family needs.",
      "imageUrl": "assets/places/pharmacy-stachus-apotheke.png",
      "isPhoto": true
    },
    {
      "id": "pharmacy-apotheke-schwabing-nord",
      "category": "pharmacy",
      "name": "Apotheke Schwabing Nord",
      "rating": 4.5,
      "ratingCount": 45,
      "address": "Ungererstr. 175, 80805 Muenchen",
      "lat": 48.1845,
      "lng": 11.5925,
      "neighborhood": "Schwabing (Alte Heide)",
      "description": "A large, very well-stocked pharmacy in northern Schwabing with several tills so families rarely wait long, plus a great cosmetics range and fast medication ordering. Open until 8pm on weekdays and on Saturdays too, which is handy for busy parents.",
      "imageUrl": "assets/places/pharmacy-apotheke-schwabing-nord.png",
      "isPhoto": true
    },
    {
      "id": "pharmacy-spitzweg-apotheke",
      "category": "pharmacy",
      "name": "Spitzweg Apotheke",
      "rating": 4.3,
      "ratingCount": 40,
      "address": "Hohenzollernstr. 93, 80796 Muenchen",
      "lat": 48.1623,
      "lng": 11.5728,
      "neighborhood": "Schwabing-West",
      "description": "A charming, well-regarded pharmacy in the heart of Schwabing-West right by Hohenzollernplatz, praised for quick help, good advice and easy reachability. A lovely local stop for families living in or visiting the lively Hohenzollernstrasse area.",
      "imageUrl": "assets/places/pharmacy-spitzweg-apotheke.png",
      "isPhoto": true
    },
    {
      "id": "pharmacy-glockenbach-apotheke",
      "category": "pharmacy",
      "name": "Glockenbach-Apotheke",
      "rating": 4.6,
      "ratingCount": 55,
      "address": "Holzstr. 19, 80469 Muenchen",
      "lat": 48.1303,
      "lng": 11.5728,
      "neighborhood": "Isarvorstadt (Glockenbachviertel)",
      "description": "Often called one of the friendliest pharmacies in Munich, this welcoming spot in the trendy Glockenbachviertel offers warm, personal advice for the whole family. Conveniently located near the old southern cemetery and Isar riverside walks.",
      "imageUrl": "assets/places/pharmacy-glockenbach-apotheke.png",
      "isPhoto": true
    },
    {
      "id": "pharmacy-st-sebastian-apotheke",
      "category": "pharmacy",
      "name": "St. Sebastian-Apotheke",
      "rating": 4.3,
      "ratingCount": 30,
      "address": "Schleissheimer Str. 163, 80797 Muenchen",
      "lat": 48.1685,
      "lng": 11.5645,
      "neighborhood": "Schwabing-West",
      "description": "A reliable, friendly neighbourhood pharmacy in Schwabing-West that's a dependable everyday stop for local families needing prescriptions and quick advice. Open early on weekdays, making morning errands easy before school or work.",
      "imageUrl": "assets/defaults/pharmacy.png",
      "isPhoto": false
    }
  ]
};
