/* Munich place data — 152 places. Center = hotel (Goethestraße 18, Ludwigsvorstadt). New places (added 97) show a per-type gradient+icon until a real photo is found. */
window.MUNICH_DATA = {
  "city": "Munich, Germany",
  "center": {
    "lat": 48.1369847,
    "lng": 11.5585181
  },
  "categories": [
    {
      "key": "monument",
      "label": "monuments, landmarks & historic sites",
      "food": false
    },
    {
      "key": "restaurant",
      "label": "restaurants & beer gardens",
      "food": true
    },
    {
      "key": "bakery",
      "label": "bakeries, konditoreien & cafes",
      "food": true
    },
    {
      "key": "active",
      "label": "active attractions & outdoor activities",
      "food": false
    },
    {
      "key": "supermarket",
      "label": "supermarkets & grocery stores",
      "food": false
    },
    {
      "key": "pharmacy",
      "label": "pharmacies (Apotheken)",
      "food": false
    }
  ],
  "places": [
    {
      "id": "monument-marienplatz",
      "category": "monument",
      "name": "Marienplatz",
      "rating": 4.7,
      "ratingCount": 95000,
      "address": "Marienplatz 1, 80331 München",
      "lat": 48.137154,
      "lng": 11.575382,
      "neighborhood": "Altstadt-Lehel (Old Town)",
      "description": "Munich's lively central square and the heart of the old town, where families gather to watch the famous Glockenspiel chime from the New Town Hall tower. There's plenty of open space, street performers and ice cream nearby, making it a perfect first stop for kids.",
      "imageUrl": "assets/places/monument-marienplatz.jpg",
      "isPhoto": true
    },
    {
      "id": "monument-frauenkirche-cathedral-of-our-dear-lady",
      "category": "monument",
      "name": "Frauenkirche (Cathedral of Our Dear Lady)",
      "rating": 4.6,
      "ratingCount": 22000,
      "address": "Frauenplatz 12, 80331 München",
      "lat": 48.138658,
      "lng": 11.573953,
      "neighborhood": "Altstadt-Lehel (Old Town)",
      "description": "This grand Gothic cathedral with its twin onion-domed towers is the unmistakable symbol of Munich's skyline. Step inside to spot the legendary 'Devil's Footprint' on the floor, a fun little mystery that delights curious kids.",
      "imageUrl": "assets/places/monument-frauenkirche-cathedral-of-our-dear-lady.jpg",
      "isPhoto": true
    },
    {
      "id": "monument-nymphenburg-palace-schloss-nymphenburg",
      "category": "monument",
      "name": "Nymphenburg Palace (Schloss Nymphenburg)",
      "rating": 4.6,
      "ratingCount": 35000,
      "address": "Schloss Nymphenburg 1, 80638 München",
      "lat": 48.158303,
      "lng": 11.503352,
      "neighborhood": "Neuhausen-Nymphenburg",
      "description": "A magnificent Baroque summer palace surrounded by sprawling gardens, canals and fountains where families can stroll, picnic and watch swans glide by. The lavish royal rooms and the whimsical 'Beauty Gallery' make it a storybook day out.",
      "imageUrl": "assets/places/monument-nymphenburg-palace-schloss-nymphenburg.jpg",
      "isPhoto": true
    },
    {
      "id": "monument-munich-residenz",
      "category": "monument",
      "name": "Munich Residenz",
      "rating": 4.7,
      "ratingCount": 30000,
      "address": "Residenzstraße 1, 80333 München",
      "lat": 48.141329,
      "lng": 11.578289,
      "neighborhood": "Altstadt-Lehel (Old Town)",
      "description": "Once the royal palace of Bavaria's kings, this enormous complex dazzles with opulent halls, courtyards and a sparkling treasury full of crowns and jewels. Kids love hunting for the gilded grotto and the glittering gemstones on the family-friendly audio tour.",
      "imageUrl": "assets/places/monument-munich-residenz.jpg",
      "isPhoto": true
    },
    {
      "id": "monument-siegestor-victory-gate",
      "category": "monument",
      "name": "Siegestor (Victory Gate)",
      "rating": 4.6,
      "ratingCount": 6500,
      "address": "Leopoldstraße 1, 80539 München",
      "lat": 48.151667,
      "lng": 11.581389,
      "neighborhood": "Maxvorstadt / Schwabing",
      "description": "A grand triumphal arch crowned by a lion-drawn chariot, often compared to the Arc de Triomphe in Paris. It marks the lively gateway to the student district of Schwabing and is a striking, free photo stop for the whole family.",
      "imageUrl": "assets/places/monument-siegestor-victory-gate.jpg",
      "isPhoto": true
    },
    {
      "id": "monument-asamkirche-st-johann-nepomuk",
      "category": "monument",
      "name": "Asamkirche (St. Johann Nepomuk)",
      "rating": 4.7,
      "ratingCount": 9000,
      "address": "Sendlinger Straße 32, 80331 München",
      "lat": 48.135222,
      "lng": 11.570722,
      "neighborhood": "Hackenviertel (Old Town)",
      "description": "A tiny but breathtaking Baroque-Rococo church tucked between shops, overflowing with gold, frescoes and dramatic detail on every surface. Its jewel-box interior wows visitors of all ages in just a few awe-filled minutes.",
      "imageUrl": "assets/places/monument-asamkirche-st-johann-nepomuk.jpg",
      "isPhoto": true
    },
    {
      "id": "monument-odeonsplatz",
      "category": "monument",
      "name": "Odeonsplatz",
      "rating": 4.6,
      "ratingCount": 11000,
      "address": "Odeonsplatz, 80539 München",
      "lat": 48.142222,
      "lng": 11.5775,
      "neighborhood": "Altstadt-Lehel (Old Town)",
      "description": "An elegant Italian-inspired square framed by the bright-yellow Theatine Church and the grand Feldherrnhalle loggia. It's a wide, open space great for family photos and a relaxed start to a walk up the stately Ludwigstraße.",
      "imageUrl": "assets/places/monument-odeonsplatz.jpg",
      "isPhoto": true
    },
    {
      "id": "monument-st-peter-s-church-alter-peter",
      "category": "monument",
      "name": "St. Peter's Church (Alter Peter)",
      "rating": 4.7,
      "ratingCount": 18000,
      "address": "Rindermarkt 1, 80331 München",
      "lat": 48.136469,
      "lng": 11.575941,
      "neighborhood": "Altstadt-Lehel (Old Town)",
      "description": "Munich's oldest parish church, whose 91-metre tower 'Alter Peter' rewards those who climb its roughly 300 steps with sweeping views of the old town and, on clear days, the Alps. A fun little adventure for energetic kids right beside Marienplatz.",
      "imageUrl": "assets/places/monument-st-peter-s-church-alter-peter.jpg",
      "isPhoto": true
    },
    {
      "id": "monument-sendlinger-tor",
      "category": "monument",
      "name": "Sendlinger Tor",
      "rating": 4.5,
      "ratingCount": 6000,
      "address": "Sendlinger-Tor-Platz 1, 80336 München",
      "lat": 48.133611,
      "lng": 11.567222,
      "neighborhood": "Hackenviertel / Isarvorstadt",
      "description": "One of Munich's three surviving medieval city gates, beautifully restored with twin Gothic towers marking the southern edge of the old town. It's a great free landmark to walk through on the way to the shops and Christmas market on Sendlinger Straße.",
      "imageUrl": "assets/places/monument-sendlinger-tor.jpg",
      "isPhoto": true
    },
    {
      "id": "monument-chinesischer-turm-chinese-tower-englischer-garten",
      "category": "monument",
      "name": "Chinesischer Turm (Chinese Tower), Englischer Garten",
      "rating": 4.5,
      "ratingCount": 13000,
      "address": "Englischer Garten 3, 80538 München",
      "lat": 48.151931,
      "lng": 11.592235,
      "neighborhood": "Englischer Garten (Schwabing-Freimann)",
      "description": "A charming wooden pagoda-style tower at the heart of the vast English Garden, surrounded by one of Munich's largest and most relaxed beer gardens. Families can spread out on the lawns, enjoy Bavarian snacks and let the kids run free in the huge park.",
      "imageUrl": "assets/places/monument-chinesischer-turm-chinese-tower-englischer-garten.jpg",
      "isPhoto": true
    },
    {
      "id": "restaurant-hofbrauhaus-munchen",
      "category": "restaurant",
      "name": "Hofbräuhaus München",
      "rating": 4.4,
      "ratingCount": 90000,
      "address": "Platzl 9, 80331 München",
      "lat": 48.1374,
      "lng": 11.5797,
      "neighborhood": "Altstadt-Lehel (Platzl, city center)",
      "description": "Munich's most famous beer hall, founded in 1589, with a lively festive atmosphere, live Bavarian brass music and big plates of pretzels, sausages and roast chicken. The huge communal tables and cheerful buzz make it an easy, memorable stop for families exploring the old town.",
      "imageUrl": "assets/places/restaurant-hofbrauhaus-munchen.jpg",
      "isPhoto": true
    },
    {
      "id": "restaurant-augustiner-keller",
      "category": "restaurant",
      "name": "Augustiner-Keller",
      "rating": 4.5,
      "ratingCount": 18000,
      "address": "Arnulfstraße 52, 80335 München",
      "lat": 48.1442,
      "lng": 11.5497,
      "neighborhood": "Maxvorstadt (near Hauptbahnhof)",
      "description": "A beloved, leafy beer garden under old chestnut trees serving Augustiner's famous Edelstoff straight from wooden barrels alongside hearty Bavarian classics. With thousands of shaded seats and a relaxed local feel, there's plenty of room for kids to roam while grown-ups enjoy a stein.",
      "imageUrl": "assets/places/restaurant-augustiner-keller.jpg",
      "isPhoto": true
    },
    {
      "id": "restaurant-wirtshaus-in-der-au",
      "category": "restaurant",
      "name": "Wirtshaus in der Au",
      "rating": 4.5,
      "ratingCount": 6500,
      "address": "Lilienstraße 51, 81669 München",
      "lat": 48.1289,
      "lng": 11.5836,
      "neighborhood": "Au-Haidhausen",
      "description": "A warm, historic Bavarian tavern open since 1901 that is famous for its dumplings, roast duck and organic local fare near the Deutsches Museum. The cozy, welcoming atmosphere and classic comfort food make it a relaxed choice for a family dinner.",
      "imageUrl": "assets/places/restaurant-wirtshaus-in-der-au.jpg",
      "isPhoto": true
    },
    {
      "id": "restaurant-biergarten-am-chinesischen-turm",
      "category": "restaurant",
      "name": "Biergarten am Chinesischen Turm",
      "rating": 4.3,
      "ratingCount": 14000,
      "address": "Englischer Garten 3, 80538 München",
      "lat": 48.1525,
      "lng": 11.5923,
      "neighborhood": "Schwabing (Englischer Garten)",
      "description": "Munich's second-largest beer garden, set around a charming wooden pagoda in the English Garden with around 7,000 seats shaded by chestnut trees. On weekends a Bavarian band plays from the tower, and there's space for kids to run and a nearby carousel, making it a classic family outing.",
      "imageUrl": "assets/places/restaurant-biergarten-am-chinesischen-turm.jpg",
      "isPhoto": true
    },
    {
      "id": "restaurant-koniglicher-hirschgarten",
      "category": "restaurant",
      "name": "Königlicher Hirschgarten",
      "rating": 4.4,
      "ratingCount": 9000,
      "address": "Hirschgarten 1, 80639 München",
      "lat": 48.1539,
      "lng": 11.5147,
      "neighborhood": "Neuhausen-Nymphenburg",
      "description": "The largest beer garden in the world with around 8,000 seats under giant chestnut trees, run as a Bavarian restaurant since the late 18th century. Best of all for families, there's an adjoining deer enclosure, playgrounds and a carousel, so children are entertained while parents enjoy Augustiner beer and Wirtshaus classics.",
      "imageUrl": "assets/places/restaurant-koniglicher-hirschgarten.jpg",
      "isPhoto": true
    },
    {
      "id": "restaurant-seehaus-im-englischen-garten",
      "category": "restaurant",
      "name": "Seehaus im Englischen Garten",
      "rating": 4.3,
      "ratingCount": 9500,
      "address": "Kleinhesselohe 3, 80802 München",
      "lat": 48.1626,
      "lng": 11.5963,
      "neighborhood": "Schwabing (Englischer Garten)",
      "description": "A scenic restaurant and beer garden right on the Kleinhesseloher lake in the English Garden, with terraces overlooking the water and rowboats for hire nearby. Families can grab pretzels, Obatzda and roast pork in the self-service beer garden or enjoy a sit-down meal with a lovely lakeside view.",
      "imageUrl": "assets/places/restaurant-seehaus-im-englischen-garten.jpg",
      "isPhoto": true
    },
    {
      "id": "restaurant-paulaner-am-nockherberg",
      "category": "restaurant",
      "name": "Paulaner am Nockherberg",
      "rating": 4.2,
      "ratingCount": 8000,
      "address": "Hochstraße 77, 81541 München",
      "lat": 48.1226,
      "lng": 11.5856,
      "neighborhood": "Au-Haidhausen",
      "description": "The flagship Paulaner brewery restaurant and beer garden, famous as the home of Munich's strong-beer festival, with a chestnut-shaded garden seating around 3,000. Big Bavarian portions, a sunny terrace and an easygoing atmosphere make it a comfortable spot for a family meal east of the Isar.",
      "imageUrl": "assets/places/restaurant-paulaner-am-nockherberg.jpg",
      "isPhoto": true
    },
    {
      "id": "restaurant-augustiner-braustuben",
      "category": "restaurant",
      "name": "Augustiner Bräustuben",
      "rating": 4.5,
      "ratingCount": 8000,
      "address": "Landsberger Straße 19, 80339 München",
      "lat": 48.1391,
      "lng": 11.5409,
      "neighborhood": "Ludwigsvorstadt-Isarvorstadt (Westend)",
      "description": "An authentic, down-to-earth Bavarian beer hall set inside the historic Augustiner brewery, where you can sometimes glimpse the brewery's stately horses. Loved by locals for fresh Augustiner beer and honest, hearty food at fair prices, it offers a genuine Munich experience away from the tourist crowds.",
      "imageUrl": "assets/places/restaurant-augustiner-braustuben.jpg",
      "isPhoto": true
    },
    {
      "id": "restaurant-l-osteria-munchen-leopoldstrasse",
      "category": "restaurant",
      "name": "L'Osteria München Leopoldstraße",
      "rating": 4.1,
      "ratingCount": 6489,
      "address": "Leopoldstraße 28a, 80802 München",
      "lat": 48.1552055,
      "lng": 11.5840263,
      "neighborhood": "Schwabing",
      "description": "A lively, relaxed Italian spot on bustling Leopoldstraße famous for its enormous thin-crust pizzas that spill over the plate and are perfect for sharing. The casual atmosphere, fair prices and kid-friendly menu make it a reliable, fun choice for families wanting a break from Bavarian fare.",
      "imageUrl": "assets/places/restaurant-l-osteria-munchen-leopoldstrasse.jpg",
      "isPhoto": true
    },
    {
      "id": "bakery-rischart-cafe-am-marienplatz",
      "category": "bakery",
      "name": "Rischart Café am Marienplatz",
      "rating": 4.1,
      "ratingCount": 3500,
      "address": "Marienplatz 18, 80331 München",
      "lat": 48.1369,
      "lng": 11.5755,
      "neighborhood": "Altstadt (Marienplatz)",
      "description": "A beloved five-generation Munich bakery-café right on Marienplatz, with cases full of cakes, tarts and pastries and unbeatable upstairs views of the Glockenspiel that delight kids and grown-ups alike. A perfect coffee-and-cake stop in the heart of the old town.",
      "imageUrl": "assets/places/bakery-rischart-cafe-am-marienplatz.jpg",
      "isPhoto": true
    },
    {
      "id": "bakery-schmalznudel-cafe-frischhut",
      "category": "bakery",
      "name": "Schmalznudel - Café Frischhut",
      "rating": 4.4,
      "ratingCount": 579,
      "address": "Prälat-Zistl-Straße 8, 80331 München",
      "lat": 48.1348883,
      "lng": 11.5745521,
      "neighborhood": "Altstadt (Viktualienmarkt)",
      "description": "A cozy, nostalgic institution near the Viktualienmarkt famous for its freshly fried Schmalznudel and Bavarian Auszogne pastries, served warm with coffee. Kids love watching the dough fried right at the counter (cash only).",
      "imageUrl": "assets/places/bakery-schmalznudel-cafe-frischhut.jpg",
      "isPhoto": true
    },
    {
      "id": "bakery-julius-brantner-brothandwerk",
      "category": "bakery",
      "name": "Julius Brantner Brothandwerk",
      "rating": 4.8,
      "ratingCount": 1180,
      "address": "Nordendstraße 23, 80801 München",
      "lat": 48.1553434,
      "lng": 11.5750642,
      "neighborhood": "Schwabing",
      "description": "Munich's most celebrated artisan baker, where slow-fermented organic sourdough loaves and buttery pastries are baked behind glass in a transparent open bakery. Worth the weekend queue for a warm loaf to share with the family.",
      "imageUrl": "assets/places/bakery-julius-brantner-brothandwerk.jpg",
      "isPhoto": true
    },
    {
      "id": "bakery-boulangerie-dompierre",
      "category": "bakery",
      "name": "Boulangerie Dompierre",
      "rating": 4.3,
      "ratingCount": 1800,
      "address": "Hans-Sachs-Straße 1, 80469 München",
      "lat": 48.132,
      "lng": 11.5707,
      "neighborhood": "Glockenbachviertel (Isarvorstadt)",
      "description": "Munich's go-to French bakery in the lively Glockenbach quarter, known for crackly baguettes, flaky croissants and irresistible éclairs and apple tarts. A charming, friendly spot for a French-style family treat.",
      "imageUrl": "assets/places/bakery-boulangerie-dompierre.jpg",
      "isPhoto": true
    },
    {
      "id": "bakery-cafe-luitpold",
      "category": "bakery",
      "name": "Café Luitpold",
      "rating": 3.9,
      "ratingCount": 4600,
      "address": "Brienner Straße 11, 80333 München",
      "lat": 48.143,
      "lng": 11.5743,
      "neighborhood": "Maxvorstadt",
      "description": "A grand, historic Viennese-style coffee house founded in 1888, famed for its house-made pralines, elegant cakes and sunny glasshouse atrium. A lovely place to linger over coffee and a slice of torte with the family.",
      "imageUrl": "assets/places/bakery-cafe-luitpold.jpg",
      "isPhoto": true
    },
    {
      "id": "bakery-conditorei-cafe-kreutzkamm",
      "category": "bakery",
      "name": "Conditorei Café Kreutzkamm",
      "rating": 4.2,
      "ratingCount": 600,
      "address": "Pacellistraße 5, 80333 München",
      "lat": 48.1394,
      "lng": 11.5718,
      "neighborhood": "Altstadt",
      "description": "A traditional family pastry shop with roots dating to 1825, renowned for its handmade Baumkuchen, Prinzregententorte and classic German cakes just steps from Marienplatz. An old-world coffee-and-cake treat the whole family can enjoy.",
      "imageUrl": "assets/places/bakery-conditorei-cafe-kreutzkamm.jpg",
      "isPhoto": true
    },
    {
      "id": "bakery-brot-feinbackerei-neulinger",
      "category": "bakery",
      "name": "Brot & Feinbäckerei Neulinger",
      "rating": 4.2,
      "ratingCount": 228,
      "address": "Volkartstraße 48, 80636 München",
      "lat": 48.1569432,
      "lng": 11.539088,
      "neighborhood": "Neuhausen-Nymphenburg",
      "description": "A certified-organic neighborhood bakery in Neuhausen where naturally leavened breads are baked in a master baker's own wood-fired oven. A friendly, down-to-earth spot for fresh bread, pretzels and pastries.",
      "imageUrl": "assets/places/bakery-brot-feinbackerei-neulinger.jpg",
      "isPhoto": true
    },
    {
      "id": "bakery-cafe-glockenspiel",
      "category": "bakery",
      "name": "Café Glockenspiel",
      "rating": 4,
      "ratingCount": 900,
      "address": "Marienplatz 28, 80331 München",
      "lat": 48.1372,
      "lng": 11.576,
      "neighborhood": "Altstadt (Marienplatz)",
      "description": "A relaxed top-floor café overlooking Marienplatz, beloved for hearty breakfasts, good coffee and homemade strudel with a front-row view of the Rathaus Glockenspiel. A memorable, family-friendly perch above the bustle.",
      "imageUrl": "assets/places/bakery-cafe-glockenspiel.jpg",
      "isPhoto": true
    },
    {
      "id": "active-englischer-garten",
      "category": "active",
      "name": "Englischer Garten",
      "rating": 4.7,
      "ratingCount": 95000,
      "address": "Englischer Garten 2, 80538 München",
      "lat": 48.1642,
      "lng": 11.6056,
      "neighborhood": "Schwabing / Lehel",
      "description": "One of the largest urban parks in the world, with endless meadows, shady tree-lined paths, streams, and a beer garden by the Chinese Tower. Perfect for a family stroll, a bike ride, a picnic, or watching the surfers on the Eisbach.",
      "imageUrl": "assets/places/active-englischer-garten.jpg",
      "isPhoto": true
    },
    {
      "id": "active-eisbachwelle",
      "category": "active",
      "name": "Eisbachwelle",
      "rating": 4.7,
      "ratingCount": 3500,
      "address": "Prinzregentenstraße 1, 80538 München",
      "lat": 48.1437,
      "lng": 11.5887,
      "neighborhood": "Lehel",
      "description": "Munich's famous standing river wave at the southern edge of the English Garden, where wetsuited surfers ride year-round. It's free to watch and an unforgettable, only-in-Munich spectacle for kids and grown-ups alike.",
      "imageUrl": "assets/places/active-eisbachwelle.jpg",
      "isPhoto": true
    },
    {
      "id": "active-olympiapark-munchen",
      "category": "active",
      "name": "Olympiapark München",
      "rating": 4.6,
      "ratingCount": 60000,
      "address": "Spiridon-Louis-Ring 21, 80809 München",
      "lat": 48.1748,
      "lng": 11.5501,
      "neighborhood": "Milbertshofen-Am Hart / Olympiapark",
      "description": "The sweeping green grounds of the 1972 Olympics, with grassy hills, a lake, playgrounds, and the climbable Olympiaberg for great city views. A wonderful spot for families to walk, cycle, fly kites, or paddle on the lake.",
      "imageUrl": "assets/places/active-olympiapark-munchen.jpg",
      "isPhoto": true
    },
    {
      "id": "active-boulderwelt-munchen-ost",
      "category": "active",
      "name": "Boulderwelt München Ost",
      "rating": 4.6,
      "ratingCount": 4200,
      "address": "Hanne-Hiob-Straße 4, 81671 München",
      "lat": 48.1235,
      "lng": 11.6082,
      "neighborhood": "Berg am Laim",
      "description": "One of the world's largest bouldering gyms, spanning multiple floors of colorful walls for every level plus a dedicated kids' area. A great rainy-day adventure where the whole family can climb, play, and refuel in the cafe.",
      "imageUrl": "assets/places/active-boulderwelt-munchen-ost.jpg",
      "isPhoto": true
    },
    {
      "id": "active-flaucher",
      "category": "active",
      "name": "Flaucher",
      "rating": 4.6,
      "ratingCount": 4000,
      "address": "Isarauen 8, 81379 München",
      "lat": 48.1031,
      "lng": 11.5447,
      "neighborhood": "Sendling / Thalkirchen",
      "description": "A beloved stretch of the Isar's wild riverbanks with gravel beaches, shallow water, and forest, ideal for paddling, barbecues, and lazy summer afternoons. There's even a classic beer garden tucked among the trees for families.",
      "imageUrl": "assets/places/active-flaucher.jpg",
      "isPhoto": true
    },
    {
      "id": "active-westpark",
      "category": "active",
      "name": "Westpark",
      "rating": 4.6,
      "ratingCount": 12379,
      "address": "Pressburger Straße 19, 81373 München",
      "lat": 48.1231,
      "lng": 11.5137,
      "neighborhood": "Sendling-Westpark",
      "description": "A beautifully landscaped park with lakes, an East Asian garden, playgrounds, and miles of walking and cycling paths. In summer there's open-air cinema and two beer gardens, making it a relaxed family favorite.",
      "imageUrl": "assets/places/active-westpark.jpg",
      "isPhoto": true
    },
    {
      "id": "active-tierpark-hellabrunn",
      "category": "active",
      "name": "Tierpark Hellabrunn",
      "rating": 4.6,
      "ratingCount": 33657,
      "address": "Tierparkstraße 30, 81543 München",
      "lat": 48.0993,
      "lng": 11.5547,
      "neighborhood": "Thalkirchen-Obersendling-Forstenried",
      "description": "Set in the green Isar floodplains, this geo-zoo groups its animals by continent across spacious, natural habitats. With lots of walking, playgrounds, and a petting area, it's a full day of outdoor fun for families.",
      "imageUrl": "assets/places/active-tierpark-hellabrunn.jpg",
      "isPhoto": true
    },
    {
      "id": "active-dav-kletter-und-boulderzentrum-munchen-sud-thalkirchen",
      "category": "active",
      "name": "DAV Kletter- und Boulderzentrum München-Süd (Thalkirchen)",
      "rating": 4.6,
      "ratingCount": 2500,
      "address": "Thalkirchner Straße 207, 81371 München",
      "lat": 48.1083,
      "lng": 11.5436,
      "neighborhood": "Sendling / Thalkirchen",
      "description": "One of Europe's largest climbing and bouldering centers, with towering indoor walls, a big outdoor area, and gear rental on site. Family and beginner zones make it easy for first-timers and kids to try roped climbing safely.",
      "imageUrl": "assets/places/active-dav-kletter-und-boulderzentrum-munchen-sud-thalkirchen.jpg",
      "isPhoto": true
    },
    {
      "id": "active-schlosspark-nymphenburg",
      "category": "active",
      "name": "Schlosspark Nymphenburg",
      "rating": 4.7,
      "ratingCount": 50000,
      "address": "Schloß Nymphenburg 1, 80638 München",
      "lat": 48.1583,
      "lng": 11.5033,
      "neighborhood": "Neuhausen-Nymphenburg",
      "description": "The grand baroque palace gardens stretch over 180 hectares of canals, lakes, fountains, and tree-lined avenues that are free to wander. A peaceful, scenic place for long family walks, running, and spotting swans and pavilions.",
      "imageUrl": "assets/places/active-schlosspark-nymphenburg.jpg",
      "isPhoto": true
    },
    {
      "id": "active-boulderwelt-munchen-west",
      "category": "active",
      "name": "Boulderwelt München West",
      "rating": 4.7,
      "ratingCount": 1700,
      "address": "Bertha-Kipfmüller-Straße 19, 81249 München",
      "lat": 48.1493,
      "lng": 11.4452,
      "neighborhood": "Aubing-Lochhausen-Langwied",
      "description": "A modern, family-friendly bouldering gym with ever-changing routes, an outdoor climbing area, and a relaxed cafe. Often praised as one of the best spots for families to climb together in Munich.",
      "imageUrl": "assets/places/active-boulderwelt-munchen-west.jpg",
      "isPhoto": true
    },
    {
      "id": "supermarket-edeka-ernst",
      "category": "supermarket",
      "name": "EDEKA Ernst",
      "rating": 4.1,
      "ratingCount": 1700,
      "address": "Arnulfstrasse 2, 80335 Muenchen",
      "lat": 48.1419,
      "lng": 11.5556,
      "neighborhood": "Maxvorstadt",
      "description": "A big, bright supermarket right by the main station with an enormous selection and very long opening hours, making it an easy stop for families running errands at almost any hour. Wide aisles and a great fresh-produce section keep stroller-pushing parents happy.",
      "imageUrl": "assets/places/supermarket-edeka-ernst.jpg",
      "isPhoto": true
    },
    {
      "id": "supermarket-rewe-center-am-arabellapark",
      "category": "supermarket",
      "name": "REWE Center am Arabellapark",
      "rating": 3.8,
      "ratingCount": 4,
      "address": "Rosenkavalierplatz 5, 81925 Muenchen",
      "lat": 48.1525681,
      "lng": 11.6198812,
      "neighborhood": "Bogenhausen (Arabellapark)",
      "description": "One of the largest REWE stores in Munich, spread over two floors with a huge range of fresh, organic and everyday groceries plus plenty of parking. The spacious layout and friendly staff make it a stress-free spot for a full family shop.",
      "imageUrl": "assets/defaults/supermarket.png",
      "isPhoto": false
    },
    {
      "id": "supermarket-rewe-city-fuenf-hoefe",
      "category": "supermarket",
      "name": "REWE City (Fuenf Hoefe)",
      "rating": 4.1,
      "ratingCount": 900,
      "address": "Theatinerstrasse 14, 80333 Muenchen",
      "lat": 48.1404,
      "lng": 11.5739,
      "neighborhood": "Altstadt-Lehel",
      "description": "An award-winning premium supermarket tucked inside the elegant Fuenf Hoefe passage, famous for its outstanding fresh counters, fruit and vegetables. A lovely place to grab high-quality groceries while exploring the old town with the family.",
      "imageUrl": "assets/places/supermarket-rewe-city-fuenf-hoefe.jpg",
      "isPhoto": true
    },
    {
      "id": "supermarket-edeka-leopoldstrasse",
      "category": "supermarket",
      "name": "EDEKA Leopoldstrasse",
      "rating": 4.2,
      "ratingCount": 1100,
      "address": "Leopoldstrasse 41, 80802 Muenchen",
      "lat": 48.1607,
      "lng": 11.5862,
      "neighborhood": "Schwabing",
      "description": "A clean, well-stocked Edeka in the heart of lively Schwabing, praised for top-quality fruit and vegetables and fair prices. Handy for families combining a stroll along Leopoldstrasse with a quick grocery run.",
      "imageUrl": "assets/places/supermarket-edeka-leopoldstrasse.jpg",
      "isPhoto": true
    },
    {
      "id": "supermarket-vollcorner-biomarkt-maxvorstadt",
      "category": "supermarket",
      "name": "VollCorner Biomarkt Maxvorstadt",
      "rating": 4.5,
      "ratingCount": 120,
      "address": "Augustenstrasse 55, 80333 Muenchen",
      "lat": 48.1505,
      "lng": 11.5631,
      "neighborhood": "Maxvorstadt",
      "description": "A welcoming neighborhood organic market with excellent fresh produce, a fresh-food counter, regional baked goods and natural cosmetics. Friendly service and high bio quality make it a favorite for health-conscious families.",
      "imageUrl": "assets/places/supermarket-vollcorner-biomarkt-maxvorstadt.jpg",
      "isPhoto": true
    },
    {
      "id": "supermarket-vollcorner-biomarkt-nymphenburg-gern",
      "category": "supermarket",
      "name": "VollCorner Biomarkt Nymphenburg/Gern",
      "rating": 4.6,
      "ratingCount": 90,
      "address": "Nederlinger Strasse 72, 80638 Muenchen",
      "lat": 48.1672,
      "lng": 11.5189,
      "neighborhood": "Neuhausen-Nymphenburg (Gern)",
      "description": "A lovingly renovated organic store serving the leafy Gern and Nymphenburg neighborhoods since 2009, near Schloss Nymphenburg. Great regional and exotic ingredients make it a relaxed, family-friendly stop after a palace-park outing.",
      "imageUrl": "assets/places/supermarket-vollcorner-biomarkt-nymphenburg-gern.jpg",
      "isPhoto": true
    },
    {
      "id": "supermarket-tegut-gute-lebensmittel-maxvorstadt-elisenhof",
      "category": "supermarket",
      "name": "tegut... gute Lebensmittel Maxvorstadt (Elisenhof)",
      "rating": 4,
      "ratingCount": 250,
      "address": "Luitpoldstrasse 3, 80335 Muenchen",
      "lat": 48.1437,
      "lng": 11.5631,
      "neighborhood": "Maxvorstadt (Klinikviertel)",
      "description": "A spacious tegut in the Elisenhof center near the main station, with a large bio range and a good fresh fruit-and-vegetable selection. Central and easy to reach, it is a convenient choice for families shopping downtown.",
      "imageUrl": "assets/places/supermarket-tegut-gute-lebensmittel-maxvorstadt-elisenhof.jpg",
      "isPhoto": true
    },
    {
      "id": "supermarket-tegut-gute-lebensmittel-glockenbachviertel",
      "category": "supermarket",
      "name": "tegut... gute Lebensmittel Glockenbachviertel",
      "rating": 4,
      "ratingCount": 150,
      "address": "Muellerstrasse 45, 80469 Muenchen",
      "lat": 48.1322,
      "lng": 11.5708,
      "neighborhood": "Glockenbachviertel (Isarvorstadt)",
      "description": "A friendly tegut in the trendy Glockenbachviertel with a fresh-service counter and a strong organic selection. Perfect for families living or visiting in this central, walkable neighborhood.",
      "imageUrl": "assets/places/supermarket-tegut-gute-lebensmittel-glockenbachviertel.jpg",
      "isPhoto": true
    },
    {
      "id": "supermarket-tegut-gute-lebensmittel-neuperlach-perlach-plaza",
      "category": "supermarket",
      "name": "tegut... gute Lebensmittel Neuperlach (Perlach Plaza)",
      "rating": 4.3,
      "ratingCount": 300,
      "address": "Theodor-Heuss-Platz 5, 81737 Muenchen",
      "lat": 48.1006,
      "lng": 11.6447,
      "neighborhood": "Neuperlach (Ramersdorf-Perlach)",
      "description": "A modern supermarket in the basement of Perlach Plaza directly connected to the U-Bahn, with wide aisles, fresh produce and an open fresh counter. Praised as the best market in the area, it is an easy and pleasant family shop.",
      "imageUrl": "assets/places/supermarket-tegut-gute-lebensmittel-neuperlach-perlach-plaza.jpg",
      "isPhoto": true
    },
    {
      "id": "pharmacy-internationale-ludwigs-apotheke",
      "category": "pharmacy",
      "name": "Internationale Ludwigs-Apotheke",
      "rating": 4.1,
      "ratingCount": 188,
      "address": "Neuhauser Str. 11, 80331 Muenchen",
      "lat": 48.1378,
      "lng": 11.5705,
      "neighborhood": "Altstadt (Old Town)",
      "description": "A historic family-run pharmacy (since 1827) right in the pedestrian zone between Marienplatz and Stachus, with over 15,000 products in stock and multilingual staff who can advise the whole family in English, Russian, Arabic and more. Great for travellers needing hard-to-find international medications.",
      "imageUrl": "assets/places/pharmacy-internationale-ludwigs-apotheke.jpg",
      "isPhoto": true
    },
    {
      "id": "pharmacy-rathaus-apotheke-am-marienplatz",
      "category": "pharmacy",
      "name": "Rathaus-Apotheke am Marienplatz",
      "rating": 4,
      "ratingCount": 90,
      "address": "Marienplatz 8, 80331 Muenchen",
      "lat": 48.1373,
      "lng": 11.5755,
      "neighborhood": "Altstadt (Angerviertel)",
      "description": "A friendly, certified pharmacy directly on Marienplatz with English-speaking staff and quick, competent service, perfect for families exploring the city centre who need a quick remedy. Conveniently central and easy to reach by U-Bahn or S-Bahn.",
      "imageUrl": "assets/places/pharmacy-rathaus-apotheke-am-marienplatz.jpg",
      "isPhoto": true
    },
    {
      "id": "pharmacy-internationale-hauptbahnhof-apotheke",
      "category": "pharmacy",
      "name": "Internationale Hauptbahnhof Apotheke",
      "rating": 4.8,
      "ratingCount": 22,
      "address": "Bayerstr. 27, 80335 Muenchen",
      "lat": 48.1395,
      "lng": 11.5588,
      "neighborhood": "Ludwigsvorstadt (Hauptbahnhof)",
      "description": "A top-rated pharmacy just steps from Munich's main train station, praised for unhurried, friendly and competent advice and long hours (Mon-Sat until 8pm). A handy stop for arriving or departing families, with a 24-hour pickup machine for pre-ordered medication.",
      "imageUrl": "assets/places/pharmacy-internationale-hauptbahnhof-apotheke.jpg",
      "isPhoto": true
    },
    {
      "id": "pharmacy-stadtapotheke-am-hauptbahnhof",
      "category": "pharmacy",
      "name": "Stadtapotheke am Hauptbahnhof",
      "rating": 4.5,
      "ratingCount": 70,
      "address": "Goethestr. 8, 80336 Muenchen",
      "lat": 48.1361,
      "lng": 11.5613,
      "neighborhood": "Ludwigsvorstadt-Isarvorstadt",
      "description": "A welcoming neighbourhood pharmacy near the station where owner Malika Rabah and her team advise in English, Arabic and French, making it easy for international families to get the help they need. Open six days a week with friendly, patient service.",
      "imageUrl": "assets/places/pharmacy-stadtapotheke-am-hauptbahnhof.jpg",
      "isPhoto": true
    },
    {
      "id": "pharmacy-stachus-apotheke",
      "category": "pharmacy",
      "name": "Stachus-Apotheke",
      "rating": 4.2,
      "ratingCount": 60,
      "address": "Karlsplatz 4, 80335 Muenchen",
      "lat": 48.1392,
      "lng": 11.5655,
      "neighborhood": "Altstadt (Karlsplatz/Stachus)",
      "description": "A long-established pharmacy right at the busy Stachus (Karlsplatz), next to the Gloria cinema, well stocked and convenient for families shopping in the centre. Known for careful guidance on complex therapies as well as everyday family needs.",
      "imageUrl": "assets/places/pharmacy-stachus-apotheke.jpg",
      "isPhoto": true
    },
    {
      "id": "pharmacy-apotheke-schwabing-nord",
      "category": "pharmacy",
      "name": "Apotheke Schwabing Nord",
      "rating": 4.5,
      "ratingCount": 45,
      "address": "Ungererstr. 175, 80805 Muenchen",
      "lat": 48.1845,
      "lng": 11.5925,
      "neighborhood": "Schwabing (Alte Heide)",
      "description": "A large, very well-stocked pharmacy in northern Schwabing with several tills so families rarely wait long, plus a great cosmetics range and fast medication ordering. Open until 8pm on weekdays and on Saturdays too, which is handy for busy parents.",
      "imageUrl": "assets/places/pharmacy-apotheke-schwabing-nord.jpg",
      "isPhoto": true
    },
    {
      "id": "pharmacy-spitzweg-apotheke",
      "category": "pharmacy",
      "name": "Spitzweg Apotheke",
      "rating": 4.3,
      "ratingCount": 40,
      "address": "Hohenzollernstr. 93, 80796 Muenchen",
      "lat": 48.1623,
      "lng": 11.5728,
      "neighborhood": "Schwabing-West",
      "description": "A charming, well-regarded pharmacy in the heart of Schwabing-West right by Hohenzollernplatz, praised for quick help, good advice and easy reachability. A lovely local stop for families living in or visiting the lively Hohenzollernstrasse area.",
      "imageUrl": "assets/places/pharmacy-spitzweg-apotheke.jpg",
      "isPhoto": true
    },
    {
      "id": "pharmacy-glockenbach-apotheke",
      "category": "pharmacy",
      "name": "Glockenbach-Apotheke",
      "rating": 4.6,
      "ratingCount": 55,
      "address": "Holzstr. 19, 80469 Muenchen",
      "lat": 48.1303,
      "lng": 11.5728,
      "neighborhood": "Isarvorstadt (Glockenbachviertel)",
      "description": "Often called one of the friendliest pharmacies in Munich, this welcoming spot in the trendy Glockenbachviertel offers warm, personal advice for the whole family. Conveniently located near the old southern cemetery and Isar riverside walks.",
      "imageUrl": "assets/places/pharmacy-glockenbach-apotheke.jpg",
      "isPhoto": true
    },
    {
      "id": "pharmacy-st-sebastian-apotheke",
      "category": "pharmacy",
      "name": "St. Sebastian-Apotheke",
      "rating": 3.1,
      "ratingCount": 50,
      "address": "Schleissheimer Str. 163, 80797 Muenchen",
      "lat": 48.166508,
      "lng": 11.5645015,
      "neighborhood": "Schwabing-West",
      "description": "A reliable, friendly neighbourhood pharmacy in Schwabing-West that's a dependable everyday stop for local families needing prescriptions and quick advice. Open early on weekdays, making morning errands easy before school or work.",
      "imageUrl": "assets/defaults/pharmacy.png",
      "isPhoto": false
    },
    {
      "id": "monument-karlstor-stachus",
      "category": "monument",
      "name": "Karlstor (Stachus)",
      "rating": 4,
      "ratingCount": 825,
      "address": "Altstadt (Old Town), München",
      "lat": 48.1390104,
      "lng": 11.5667638,
      "neighborhood": "Altstadt (Old Town)",
      "description": "One of the three surviving medieval gates of Munich, marking the western entrance to the old town at busy Stachus square. A grand archway that makes a fun photo stop on the walk into the centre.",
      "imageUrl": "assets/places/monument-karlstor-stachus.jpg",
      "isPhoto": true
    },
    {
      "id": "monument-isartor",
      "category": "monument",
      "name": "Isartor",
      "rating": 3.8,
      "ratingCount": 118,
      "address": "Altstadt (Old Town), München",
      "lat": 48.135105,
      "lng": 11.58204,
      "neighborhood": "Altstadt (Old Town)",
      "description": "The best-preserved of Munich's medieval city gates, with a painted mural and the quirky Valentin-Karlstadt comedy museum tucked inside its tower.",
      "imageUrl": "assets/places/monument-isartor.jpg",
      "isPhoto": true
    },
    {
      "id": "monument-feldherrnhalle",
      "category": "monument",
      "name": "Feldherrnhalle",
      "rating": 4.5,
      "ratingCount": 1324,
      "address": "Altstadt-Lehel, München",
      "lat": 48.1416776,
      "lng": 11.577316,
      "neighborhood": "Altstadt-Lehel",
      "description": "A grand Italian-style loggia guarded by two bronze lions that kids love to pose beside. It frames Odeonsplatz and the start of the elegant Ludwigstraße.",
      "imageUrl": "assets/places/monument-feldherrnhalle.jpg",
      "isPhoto": true
    },
    {
      "id": "monument-theatinerkirche-st-kajetan",
      "category": "monument",
      "name": "Theatinerkirche (St. Kajetan)",
      "rating": 4.7,
      "ratingCount": 1461,
      "address": "Altstadt-Lehel, München",
      "lat": 48.1420299,
      "lng": 11.5766146,
      "neighborhood": "Altstadt-Lehel",
      "description": "A striking mustard-yellow Baroque church with twin towers and a bright dome. Its ornate white interior is calm, cool and easy to admire in a short visit.",
      "imageUrl": "assets/places/monument-theatinerkirche-st-kajetan.jpg",
      "isPhoto": true
    },
    {
      "id": "monument-st-michael-s-church-michaelskirche",
      "category": "monument",
      "name": "St. Michael's Church (Michaelskirche)",
      "rating": 4.7,
      "ratingCount": 6019,
      "address": "Altstadt (Old Town), München",
      "lat": 48.1389266,
      "lng": 11.5704194,
      "neighborhood": "Altstadt (Old Town)",
      "description": "One of the largest Renaissance churches north of the Alps, right on the pedestrian shopping street. The vast barrel-vaulted ceiling is quietly impressive for all ages.",
      "imageUrl": "assets/places/monument-st-michael-s-church-michaelskirche.jpg",
      "isPhoto": true
    },
    {
      "id": "monument-hofgarten",
      "category": "monument",
      "name": "Hofgarten",
      "rating": 4.3,
      "ratingCount": 709,
      "address": "Altstadt-Lehel, München",
      "lat": 48.1426773,
      "lng": 11.5804659,
      "neighborhood": "Altstadt-Lehel",
      "description": "A formal Renaissance garden with symmetrical paths, a domed pavilion and shady benches. A peaceful green square for a family breather right by the Residenz.",
      "imageUrl": "assets/places/monument-hofgarten.jpg",
      "isPhoto": true
    },
    {
      "id": "monument-konigsplatz",
      "category": "monument",
      "name": "Königsplatz",
      "rating": 4.6,
      "ratingCount": 9684,
      "address": "Maxvorstadt, München",
      "lat": 48.1456681,
      "lng": 11.5656895,
      "neighborhood": "Maxvorstadt",
      "description": "A grand square framed by Greek-temple-style museum buildings and the Propyläen gate. Wide open space that's great for stretching kids' legs between galleries.",
      "imageUrl": "assets/places/monument-konigsplatz.jpg",
      "isPhoto": true
    },
    {
      "id": "monument-st-ludwig-s-church-ludwigskirche",
      "category": "monument",
      "name": "St. Ludwig's Church (Ludwigskirche)",
      "rating": 4.7,
      "ratingCount": 448,
      "address": "Maxvorstadt, München",
      "lat": 48.1488494,
      "lng": 11.5812526,
      "neighborhood": "Maxvorstadt",
      "description": "A twin-towered church on Ludwigstraße famous for one of the world's largest altar frescoes. A quick, awe-inspiring peek for anyone walking near the university.",
      "imageUrl": "assets/places/monument-st-ludwig-s-church-ludwigskirche.jpg",
      "isPhoto": true
    },
    {
      "id": "monument-bavaria-statue-ruhmeshalle",
      "category": "monument",
      "name": "Bavaria Statue & Ruhmeshalle",
      "rating": 4.7,
      "ratingCount": 3905,
      "address": "Ludwigsvorstadt, München",
      "lat": 48.1306873,
      "lng": 11.5459393,
      "neighborhood": "Ludwigsvorstadt",
      "description": "A giant bronze goddess towering over the Oktoberfest meadow, with a viewing gallery inside her head. The steps and open field are a short, easy stroll from the hotel.",
      "imageUrl": "assets/places/monument-bavaria-statue-ruhmeshalle.jpg",
      "isPhoto": true
    },
    {
      "id": "monument-wittelsbacher-brunnen",
      "category": "monument",
      "name": "Wittelsbacher Brunnen",
      "rating": 4.7,
      "ratingCount": 600,
      "address": "Altstadt (Old Town), München",
      "lat": 48.1413445,
      "lng": 11.5693136,
      "neighborhood": "Altstadt (Old Town)",
      "description": "A monumental fountain of pale stone with dramatic figures riding water beasts. A refreshing landmark to pause at on the edge of Lenbachplatz.",
      "imageUrl": "assets/places/monument-wittelsbacher-brunnen.jpg",
      "isPhoto": true
    },
    {
      "id": "monument-alter-botanischer-garten",
      "category": "monument",
      "name": "Alter Botanischer Garten",
      "rating": 4.1,
      "ratingCount": 4780,
      "address": "Maxvorstadt, München",
      "lat": 48.14174,
      "lng": 11.5643701,
      "neighborhood": "Maxvorstadt",
      "description": "A small leafy park with a fountain and lawns just steps from the main station. A handy shady spot to rest little legs near the hotel.",
      "imageUrl": "assets/places/monument-alter-botanischer-garten.jpg",
      "isPhoto": true
    },
    {
      "id": "monument-justizpalast-palace-of-justice",
      "category": "monument",
      "name": "Justizpalast (Palace of Justice)",
      "rating": 4.6,
      "ratingCount": 214,
      "address": "Ludwigsvorstadt, München",
      "lat": 48.1404898,
      "lng": 11.5646876,
      "neighborhood": "Ludwigsvorstadt",
      "description": "A palatial Neo-Baroque courthouse crowned by a huge glass dome, close to Stachus. Impressive to admire from outside on the way into town.",
      "imageUrl": "assets/places/monument-justizpalast-palace-of-justice.jpg",
      "isPhoto": true
    },
    {
      "id": "monument-nationaltheater-munchen",
      "category": "monument",
      "name": "Nationaltheater München",
      "rating": 4.7,
      "ratingCount": 4034,
      "address": "Altstadt-Lehel, München",
      "lat": 48.1393491,
      "lng": 11.5787723,
      "neighborhood": "Altstadt-Lehel",
      "description": "The stately columned home of the Bavarian State Opera on Max-Joseph-Platz. Even from outside it's a photogenic classical landmark near the Residenz.",
      "imageUrl": "assets/places/monument-nationaltheater-munchen.jpg",
      "isPhoto": true
    },
    {
      "id": "monument-friedensengel-angel-of-peace",
      "category": "monument",
      "name": "Friedensengel (Angel of Peace)",
      "rating": 4.6,
      "ratingCount": 2243,
      "address": "Bogenhausen, München",
      "lat": 48.1413436,
      "lng": 11.5969927,
      "neighborhood": "Bogenhausen",
      "description": "A gleaming golden angel atop a tall column above the Isar, with terraces and fountains below. A scenic viewpoint over the river and city.",
      "imageUrl": "assets/places/monument-friedensengel-angel-of-peace.jpg",
      "isPhoto": true
    },
    {
      "id": "monument-maximilianeum",
      "category": "monument",
      "name": "Maximilianeum",
      "rating": 4.5,
      "ratingCount": 571,
      "address": "Haidhausen, München",
      "lat": 48.1364112,
      "lng": 11.5944161,
      "neighborhood": "Haidhausen",
      "description": "The grand hillside palace that houses the Bavarian parliament, overlooking the elegant Maximilianstraße. A handsome facade to admire from the bridge.",
      "imageUrl": "assets/places/monument-maximilianeum.jpg",
      "isPhoto": true
    },
    {
      "id": "monument-propylaen",
      "category": "monument",
      "name": "Propyläen",
      "rating": null,
      "ratingCount": null,
      "address": "Maxvorstadt, München",
      "lat": 48.1460577,
      "lng": 11.5642555,
      "neighborhood": "Maxvorstadt",
      "description": "A monumental Greek-style gateway of columns and winged reliefs anchoring Königsplatz. A dramatic backdrop for photos among the museums.",
      "imageUrl": "assets/places/monument-propylaen.jpg",
      "isPhoto": true
    },
    {
      "id": "monument-monopteros",
      "category": "monument",
      "name": "Monopteros",
      "rating": 4.7,
      "ratingCount": 3616,
      "address": "Schwabing (English Garden), München",
      "lat": 48.1498803,
      "lng": 11.5909208,
      "neighborhood": "Schwabing (English Garden)",
      "description": "A little Greek-style temple on a grassy hill in the English Garden with a lovely view over the city skyline. A favourite family picnic and kite-flying spot.",
      "imageUrl": "assets/places/monument-monopteros.jpg",
      "isPhoto": true
    },
    {
      "id": "monument-burgersaalkirche",
      "category": "monument",
      "name": "Bürgersaalkirche",
      "rating": 4.7,
      "ratingCount": 350,
      "address": "Altstadt (Old Town), München",
      "lat": 48.1390184,
      "lng": 11.5682512,
      "neighborhood": "Altstadt (Old Town)",
      "description": "A modest church on the shopping street with a beautiful upper prayer hall and the tomb of beloved priest Rupert Mayer. A quiet surprise amid the bustle.",
      "imageUrl": "assets/places/monument-burgersaalkirche.jpg",
      "isPhoto": true
    },
    {
      "id": "monument-sankt-anna-kirche-lehel",
      "category": "monument",
      "name": "Sankt-Anna-Kirche (Lehel)",
      "rating": 4.7,
      "ratingCount": 104,
      "address": "Lehel, München",
      "lat": 48.1396562,
      "lng": 11.5879211,
      "neighborhood": "Lehel",
      "description": "A warm Baroque parish church in the leafy Lehel quarter with a bright, uplifting interior. An easy, calm stop near the river museums.",
      "imageUrl": "assets/places/monument-sankt-anna-kirche-lehel.jpg",
      "isPhoto": true
    },
    {
      "id": "restaurant-der-pschorr",
      "category": "restaurant",
      "name": "Der Pschorr",
      "rating": 4.2,
      "ratingCount": 7850,
      "address": "Altstadt (Viktualienmarkt), München",
      "lat": 48.1347514,
      "lng": 11.5751968,
      "neighborhood": "Altstadt (Viktualienmarkt)",
      "description": "A lively Bavarian brewery restaurant on the Viktualienmarkt with hearty roasts, pretzels and its own beer garden. Bustling, family-friendly and full of local flavour.",
      "imageUrl": "assets/places/restaurant-der-pschorr.jpg",
      "isPhoto": true
    },
    {
      "id": "restaurant-spatenhaus-an-der-oper",
      "category": "restaurant",
      "name": "Spatenhaus an der Oper",
      "rating": 4.3,
      "ratingCount": 5993,
      "address": "Altstadt-Lehel, München",
      "lat": 48.1398289,
      "lng": 11.5773071,
      "neighborhood": "Altstadt-Lehel",
      "description": "A refined but welcoming Bavarian tavern opposite the opera house, with schnitzel, dumplings and a view of Max-Joseph-Platz.",
      "imageUrl": "assets/places/restaurant-spatenhaus-an-der-oper.jpg",
      "isPhoto": true
    },
    {
      "id": "restaurant-weisses-brauhaus-schneider",
      "category": "restaurant",
      "name": "Weisses Bräuhaus (Schneider)",
      "rating": 4.4,
      "ratingCount": 16181,
      "address": "Altstadt (Old Town), München",
      "lat": 48.1363952,
      "lng": 11.5784219,
      "neighborhood": "Altstadt (Old Town)",
      "description": "The home of Schneider wheat beer, famous for roast pork and veal sausages in a boisterous old-Munich setting. A true Bavarian institution.",
      "imageUrl": "assets/places/restaurant-weisses-brauhaus-schneider.jpg",
      "isPhoto": true
    },
    {
      "id": "restaurant-nurnberger-bratwurst-glockl-am-dom",
      "category": "restaurant",
      "name": "Nürnberger Bratwurst Glöckl am Dom",
      "rating": 4.3,
      "ratingCount": 5254,
      "address": "Altstadt (Old Town), München",
      "lat": 48.138186,
      "lng": 11.5741404,
      "neighborhood": "Altstadt (Old Town)",
      "description": "A snug half-timbered tavern by the Frauenkirche serving little Nuremberg sausages grilled over beechwood. Cosy, cheerful and great for sharing plates.",
      "imageUrl": "assets/defaults/restaurant.png",
      "isPhoto": false
    },
    {
      "id": "restaurant-andechser-am-dom",
      "category": "restaurant",
      "name": "Andechser am Dom",
      "rating": 4.3,
      "ratingCount": 4350,
      "address": "Altstadt (Old Town), München",
      "lat": 48.1382365,
      "lng": 11.5737748,
      "neighborhood": "Altstadt (Old Town)",
      "description": "Monastery beer and hearty Bavarian food beside the cathedral, with a sunny terrace. Relaxed and reliably tasty for the whole family.",
      "imageUrl": "assets/defaults/restaurant.png",
      "isPhoto": false
    },
    {
      "id": "restaurant-hofbraukeller-am-wiener-platz",
      "category": "restaurant",
      "name": "Hofbräukeller am Wiener Platz",
      "rating": 4.4,
      "ratingCount": 8722,
      "address": "Haidhausen, München",
      "lat": 48.1344,
      "lng": 11.5931,
      "neighborhood": "Haidhausen",
      "description": "A grand beer hall with a huge chestnut-shaded beer garden and playground across the river. Roomy and welcoming for families with kids.",
      "imageUrl": "assets/places/restaurant-hofbraukeller-am-wiener-platz.jpg",
      "isPhoto": true
    },
    {
      "id": "restaurant-lowenbraukeller",
      "category": "restaurant",
      "name": "Löwenbräukeller",
      "rating": 4.3,
      "ratingCount": 9323,
      "address": "Maxvorstadt, München",
      "lat": 48.1481139,
      "lng": 11.5583203,
      "neighborhood": "Maxvorstadt",
      "description": "A palatial beer hall and garden at Stiglmaierplatz serving classic roasts and giant pretzels. Festive, spacious and easy-going.",
      "imageUrl": "assets/places/restaurant-lowenbraukeller.jpg",
      "isPhoto": true
    },
    {
      "id": "restaurant-paulaner-brauhaus",
      "category": "restaurant",
      "name": "Paulaner Bräuhaus",
      "rating": 4.3,
      "ratingCount": 1888,
      "address": "Isarvorstadt, München",
      "lat": 48.126042,
      "lng": 11.5595212,
      "neighborhood": "Isarvorstadt",
      "description": "A brewpub near Kapuzinerplatz brewing its own beer and serving stick-to-your-ribs Bavarian fare. A short walk from the hotel.",
      "imageUrl": "assets/defaults/restaurant.png",
      "isPhoto": false
    },
    {
      "id": "restaurant-zum-augustiner",
      "category": "restaurant",
      "name": "Augustiner Stammhaus",
      "rating": 4.2,
      "ratingCount": 23385,
      "address": "Altstadt (Old Town), München",
      "lat": 48.1384052,
      "lng": 11.5688037,
      "neighborhood": "Altstadt (Old Town)",
      "description": "A beautiful old restaurant on the pedestrian street pouring Augustiner from the wood and plating Munich classics. Ornate rooms and a lively courtyard.",
      "imageUrl": "assets/defaults/restaurant.png",
      "isPhoto": false
    },
    {
      "id": "restaurant-fraunhofer-wirtshaus",
      "category": "restaurant",
      "name": "Fraunhofer Wirtshaus",
      "rating": 3.8,
      "ratingCount": 1243,
      "address": "Isarvorstadt, München",
      "lat": 48.1307189,
      "lng": 11.5726076,
      "neighborhood": "Isarvorstadt",
      "description": "A characterful old-Munich tavern with hearty regional cooking and homemade dumplings, near the hotel. Warm, woody and full of local charm.",
      "imageUrl": "assets/places/restaurant-fraunhofer-wirtshaus.jpg",
      "isPhoto": true
    },
    {
      "id": "restaurant-wirtshaus-zum-straubinger",
      "category": "restaurant",
      "name": "Wirtshaus zum Straubinger",
      "rating": 4.4,
      "ratingCount": 3743,
      "address": "Altstadt (Old Town), München",
      "lat": 48.133801,
      "lng": 11.5743345,
      "neighborhood": "Altstadt (Old Town)",
      "description": "A traditional corner tavern near the Viktualienmarkt with generous Bavarian plates and friendly service. Unfussy and satisfying.",
      "imageUrl": "assets/defaults/restaurant.png",
      "isPhoto": false
    },
    {
      "id": "restaurant-bratwurstherzl",
      "category": "restaurant",
      "name": "Bratwurstherzl",
      "rating": 3.9,
      "ratingCount": 2139,
      "address": "Altstadt (Viktualienmarkt), München",
      "lat": 48.1353937,
      "lng": 11.5772635,
      "neighborhood": "Altstadt (Viktualienmarkt)",
      "description": "A tiny wood-panelled spot grilling Nuremberg sausages over an open fire on the market square. Simple, delicious and very Munich.",
      "imageUrl": "assets/defaults/restaurant.png",
      "isPhoto": false
    },
    {
      "id": "restaurant-cafe-am-beethovenplatz",
      "category": "restaurant",
      "name": "Café am Beethovenplatz",
      "rating": 4.2,
      "ratingCount": 1126,
      "address": "Ludwigsvorstadt, München",
      "lat": 48.1333879,
      "lng": 11.5587693,
      "neighborhood": "Ludwigsvorstadt",
      "description": "Munich's oldest café, with live piano, cakes and full meals in a genteel setting near the hotel. Charming for a relaxed family lunch.",
      "imageUrl": "assets/defaults/restaurant.png",
      "isPhoto": false
    },
    {
      "id": "restaurant-steinheil-16",
      "category": "restaurant",
      "name": "Steinheil 16",
      "rating": 4.6,
      "ratingCount": 5000,
      "address": "Maxvorstadt, München",
      "lat": 48.1498533,
      "lng": 11.5642279,
      "neighborhood": "Maxvorstadt",
      "description": "A cheerful student-favourite serving enormous, crispy schnitzels at friendly prices. Casual, filling and fun for hungry kids.",
      "imageUrl": "assets/defaults/restaurant.png",
      "isPhoto": false
    },
    {
      "id": "restaurant-zum-durnbrau",
      "category": "restaurant",
      "name": "Zum Dürnbräu",
      "rating": 4.5,
      "ratingCount": 4000,
      "address": "Altstadt (Old Town), München",
      "lat": 48.1362214,
      "lng": 11.5801071,
      "neighborhood": "Altstadt (Old Town)",
      "description": "A historic inn tucked in a quiet lane serving Bavarian home cooking since centuries ago. Cosy and satisfying near the Isartor.",
      "imageUrl": "assets/defaults/restaurant.png",
      "isPhoto": false
    },
    {
      "id": "restaurant-augustiner-klosterwirt",
      "category": "restaurant",
      "name": "Augustiner Klosterwirt",
      "rating": 4.5,
      "ratingCount": 13000,
      "address": "Altstadt (Old Town), München",
      "lat": 48.1384542,
      "lng": 11.5722656,
      "neighborhood": "Altstadt (Old Town)",
      "description": "A roomy Augustiner tavern beside the cathedral with a big menu of Bavarian favourites. Central, easy and dependable.",
      "imageUrl": "assets/defaults/restaurant.png",
      "isPhoto": false
    },
    {
      "id": "restaurant-pfalzer-residenz-weinstube",
      "category": "restaurant",
      "name": "Pfälzer Residenz Weinstube",
      "rating": 4,
      "ratingCount": 767,
      "address": "Altstadt-Lehel, München",
      "lat": 48.1417806,
      "lng": 11.577857,
      "neighborhood": "Altstadt-Lehel",
      "description": "A rustic wine tavern in the Residenz vaults serving regional dishes by candlelight. Atmospheric arched rooms feel like a mini adventure.",
      "imageUrl": "assets/places/restaurant-pfalzer-residenz-weinstube.jpg",
      "isPhoto": true
    },
    {
      "id": "restaurant-l-osteria-theresienwiese",
      "category": "restaurant",
      "name": "L'Osteria Schwanthalerstraße",
      "rating": 4.3,
      "ratingCount": 3735,
      "address": "Ludwigsvorstadt, München",
      "lat": 48.1374949,
      "lng": 11.5482504,
      "neighborhood": "Schwanthalerhöhe",
      "description": "Big, crispy pizzas and easygoing Italian classics near the Oktoberfest meadow, a short walk from the hotel. A crowd-pleaser for families.",
      "imageUrl": "assets/defaults/restaurant.png",
      "isPhoto": false
    },
    {
      "id": "restaurant-zum-alten-markt",
      "category": "restaurant",
      "name": "Zum Alten Markt",
      "rating": 4.7,
      "ratingCount": 1281,
      "address": "Altstadt (Viktualienmarkt), München",
      "lat": 48.1352281,
      "lng": 11.5775751,
      "neighborhood": "Altstadt (Viktualienmarkt)",
      "description": "A snug traditional restaurant just off the market with seasonal Bavarian cooking and homemade desserts. Warm and welcoming.",
      "imageUrl": "assets/defaults/restaurant.png",
      "isPhoto": false
    },
    {
      "id": "restaurant-wirtshaus-ayinger-am-platzl",
      "category": "restaurant",
      "name": "Wirtshaus Ayinger am Platzl",
      "rating": 4.4,
      "ratingCount": 3836,
      "address": "Altstadt (Old Town), München",
      "lat": 48.137908,
      "lng": 11.579752,
      "neighborhood": "Altstadt (Old Town)",
      "description": "Ayinger beer and Bavarian classics opposite the Hofbräuhaus, with a bright terrace. Central and reliably hearty.",
      "imageUrl": "assets/defaults/restaurant.png",
      "isPhoto": false
    },
    {
      "id": "bakery-cafe-tambosi",
      "category": "bakery",
      "name": "Café Tambosi",
      "rating": 4,
      "ratingCount": 2530,
      "address": "Altstadt-Lehel, München",
      "lat": 48.1429189,
      "lng": 11.5782954,
      "neighborhood": "Altstadt-Lehel",
      "description": "A historic café on Odeonsplatz with an arcaded terrace, cakes and ice cream. A classic spot to watch the world go by.",
      "imageUrl": "assets/defaults/bakery.png",
      "isPhoto": false
    },
    {
      "id": "bakery-ballabeni-ice-cream",
      "category": "bakery",
      "name": "Ballabeni Ice Cream",
      "rating": 4.7,
      "ratingCount": 2731,
      "address": "Isarvorstadt, München",
      "lat": 48.1403343,
      "lng": 11.5888104,
      "neighborhood": "Isarvorstadt",
      "description": "An artisan gelateria beloved for silky, natural-flavour ice cream, a short walk from the hotel. A must for a sweet family treat.",
      "imageUrl": "assets/defaults/bakery.png",
      "isPhoto": false
    },
    {
      "id": "bakery-man-versus-machine-coffee-roasters",
      "category": "bakery",
      "name": "Man Versus Machine Coffee Roasters",
      "rating": 4.5,
      "ratingCount": 2679,
      "address": "Glockenbachviertel, München",
      "lat": 48.1309884,
      "lng": 11.5711081,
      "neighborhood": "Glockenbachviertel",
      "description": "A bright, modern specialty coffee roastery with excellent espresso and pastries. A stylish caffeine stop near the hotel.",
      "imageUrl": "assets/places/bakery-man-versus-machine-coffee-roasters.jpg",
      "isPhoto": true
    },
    {
      "id": "bakery-cafe-kosmos",
      "category": "bakery",
      "name": "Café Kosmos",
      "rating": 4.3,
      "ratingCount": 2925,
      "address": "Ludwigsvorstadt, München",
      "lat": 48.1424802,
      "lng": 11.5600193,
      "neighborhood": "Ludwigsvorstadt",
      "description": "A retro, arty café-bar near the station with cakes, drinks and a relaxed buzz. Handy and characterful close to the hotel.",
      "imageUrl": "assets/defaults/bakery.png",
      "isPhoto": false
    },
    {
      "id": "bakery-cotidiano-gartnerplatz",
      "category": "bakery",
      "name": "Cotidiano Gärtnerplatz",
      "rating": 4.3,
      "ratingCount": 4057,
      "address": "Isarvorstadt, München",
      "lat": 48.1320881,
      "lng": 11.5757135,
      "neighborhood": "Isarvorstadt",
      "description": "An airy all-day café-bakery on pretty Gärtnerplatz with fresh bread, breakfasts and cakes. Relaxed and family-welcoming.",
      "imageUrl": "assets/defaults/bakery.png",
      "isPhoto": false
    },
    {
      "id": "bakery-zeit-fur-brot",
      "category": "bakery",
      "name": "Zeit für Brot",
      "rating": null,
      "ratingCount": null,
      "address": "Maxvorstadt, München",
      "lat": 48.1499216,
      "lng": 11.5780409,
      "neighborhood": "Maxvorstadt",
      "description": "Famous for warm, gooey cinnamon rolls and hearty sourdough loaves baked on site. A sweet-smelling stop kids adore.",
      "imageUrl": "assets/defaults/bakery.png",
      "isPhoto": false
    },
    {
      "id": "bakery-der-verruckte-eismacher",
      "category": "bakery",
      "name": "Der Verrückte Eismacher",
      "rating": 4.1,
      "ratingCount": 128,
      "address": "Altstadt (Old Town), München",
      "lat": 48.1347898,
      "lng": 11.5769225,
      "neighborhood": "Altstadt (Old Town)",
      "description": "'The Crazy Ice Maker' whips up wild, inventive gelato flavours near the Isartor. A fun, surprising treat for adventurous tasters.",
      "imageUrl": "assets/defaults/bakery.png",
      "isPhoto": false
    },
    {
      "id": "bakery-rischart-am-viktualienmarkt",
      "category": "bakery",
      "name": "Rischart am Viktualienmarkt",
      "rating": 3.4,
      "ratingCount": 2036,
      "address": "Altstadt (Viktualienmarkt), München",
      "lat": 48.1361034,
      "lng": 11.5764717,
      "neighborhood": "Altstadt (Viktualienmarkt)",
      "description": "A flagship Munich bakery-café with a huge spread of breads, cakes and pastries by the market. Bright and bustling.",
      "imageUrl": "assets/defaults/bakery.png",
      "isPhoto": false
    },
    {
      "id": "bakery-backhaus-am-sendlinger-tor",
      "category": "bakery",
      "name": "Backhaus am Sendlinger Tor",
      "rating": 4,
      "ratingCount": 685,
      "address": "Altstadt (Old Town), München",
      "lat": 48.1338,
      "lng": 11.5665,
      "neighborhood": "Altstadt (Old Town)",
      "description": "A handy neighbourhood bakery for fresh pretzels, rolls and coffee by Sendlinger Tor, near the hotel. Quick and cheerful.",
      "imageUrl": "assets/defaults/bakery.png",
      "isPhoto": false
    },
    {
      "id": "bakery-cafe-guglhupf",
      "category": "bakery",
      "name": "Café Guglhupf",
      "rating": 3.8,
      "ratingCount": 1031,
      "address": "Altstadt (Old Town), München",
      "lat": 48.136,
      "lng": 11.5745,
      "neighborhood": "Altstadt (Old Town)",
      "description": "A cheerful café near the market known for its namesake Guglhupf cake and generous breakfasts. Warm and welcoming.",
      "imageUrl": "assets/defaults/bakery.png",
      "isPhoto": false
    },
    {
      "id": "bakery-julius-brantner-blumenstra-e",
      "category": "bakery",
      "name": "Julius Brantner (Blumenstraße)",
      "rating": 4.8,
      "ratingCount": 444,
      "address": "Altstadt (Old Town), München",
      "lat": 48.1361714,
      "lng": 11.5684401,
      "neighborhood": "Altstadt (Old Town)",
      "description": "A celebrated artisan bakery for crackly-crust sourdough and simple, superb pastries, close to the hotel. Small but excellent.",
      "imageUrl": "assets/defaults/bakery.png",
      "isPhoto": false
    },
    {
      "id": "bakery-sweet-spot-cafe",
      "category": "bakery",
      "name": "Sweet Spot Café",
      "rating": 4.8,
      "ratingCount": 1576,
      "address": "Ludwigsvorstadt, München",
      "lat": 48.1357968,
      "lng": 11.5776163,
      "neighborhood": "Ludwigsvorstadt",
      "description": "A friendly little café for coffee, cakes and light breakfasts, just steps from the hotel. An easy morning go-to.",
      "imageUrl": "assets/defaults/bakery.png",
      "isPhoto": false
    },
    {
      "id": "bakery-cafe-neuhausen",
      "category": "bakery",
      "name": "Café Neuhausen",
      "rating": 4.6,
      "ratingCount": 1582,
      "address": "Neuhausen, München",
      "lat": 48.1503737,
      "lng": 11.538373,
      "neighborhood": "Neuhausen",
      "description": "A relaxed local café with big brunches, cakes and a sunny terrace. A comfy neighbourhood classic.",
      "imageUrl": "assets/defaults/bakery.png",
      "isPhoto": false
    },
    {
      "id": "active-theresienwiese",
      "category": "active",
      "name": "Theresienwiese",
      "rating": 4.7,
      "ratingCount": 741,
      "address": "Ludwigsvorstadt, München",
      "lat": 48.1313385,
      "lng": 11.5494189,
      "neighborhood": "Ludwigsvorstadt",
      "description": "The vast open meadow that hosts Oktoberfest, otherwise a huge space to run, scooter and picnic — a very short walk from the hotel.",
      "imageUrl": "assets/places/active-theresienwiese.jpg",
      "isPhoto": true
    },
    {
      "id": "active-deutsches-museum",
      "category": "active",
      "name": "Deutsches Museum",
      "rating": 4.5,
      "ratingCount": 42912,
      "address": "Isarvorstadt (Museumsinsel), München",
      "lat": 48.1300409,
      "lng": 11.582909,
      "neighborhood": "Isarvorstadt (Museumsinsel)",
      "description": "One of the world's biggest science and technology museums, packed with hands-on exhibits, ships, planes and a kids' zone. A brilliant rainy-day day-out.",
      "imageUrl": "assets/places/active-deutsches-museum.jpg",
      "isPhoto": true
    },
    {
      "id": "active-viktualienmarkt",
      "category": "active",
      "name": "Viktualienmarkt",
      "rating": 4.6,
      "ratingCount": 63294,
      "address": "Altstadt (Old Town), München",
      "lat": 48.135518,
      "lng": 11.5761813,
      "neighborhood": "Altstadt (Old Town)",
      "description": "Munich's beloved open-air food market with colourful stalls, snacks, a maypole and a beer garden. A feast for the senses for all ages.",
      "imageUrl": "assets/places/active-viktualienmarkt.jpg",
      "isPhoto": true
    },
    {
      "id": "active-alter-sudfriedhof",
      "category": "active",
      "name": "Alter Südfriedhof",
      "rating": 4.8,
      "ratingCount": 257,
      "address": "Isarvorstadt, München",
      "lat": 48.1276254,
      "lng": 11.5652106,
      "neighborhood": "Isarvorstadt",
      "description": "A romantic old cemetery turned leafy park with mossy tombs and shady avenues, near the hotel. A peaceful, atmospheric stroll.",
      "imageUrl": "assets/places/active-alter-sudfriedhof.jpg",
      "isPhoto": true
    },
    {
      "id": "active-bavariapark",
      "category": "active",
      "name": "Bavariapark",
      "rating": 4.6,
      "ratingCount": 1299,
      "address": "Schwanthalerhöhe, München",
      "lat": 48.1309136,
      "lng": 11.5430036,
      "neighborhood": "Schwanthalerhöhe",
      "description": "A green park with lawns, big trees and a playground behind the Bavaria statue. A relaxed outdoor break a short walk from the hotel.",
      "imageUrl": "assets/places/active-bavariapark.jpg",
      "isPhoto": true
    },
    {
      "id": "active-mullersches-volksbad",
      "category": "active",
      "name": "Müllersches Volksbad",
      "rating": 4.4,
      "ratingCount": 2197,
      "address": "Au, München",
      "lat": 48.1322632,
      "lng": 11.5884273,
      "neighborhood": "Au",
      "description": "A stunning Art Nouveau public swimming bath with grand vaulted pools and a steam room. A gorgeous place for a family swim.",
      "imageUrl": "assets/places/active-mullersches-volksbad.jpg",
      "isPhoto": true
    },
    {
      "id": "active-bmw-welt",
      "category": "active",
      "name": "BMW Welt",
      "rating": 4.7,
      "ratingCount": 39613,
      "address": "Milbertshofen, München",
      "lat": 48.1772189,
      "lng": 11.5563758,
      "neighborhood": "Milbertshofen",
      "description": "A futuristic glass showcase of cars and motorbikes you can climb into, free to enter. Shiny, spacious and a hit with kids.",
      "imageUrl": "assets/places/active-bmw-welt.jpg",
      "isPhoto": true
    },
    {
      "id": "active-sea-life-munchen",
      "category": "active",
      "name": "Sea Life München",
      "rating": 3.9,
      "ratingCount": 13479,
      "address": "Olympiapark, München",
      "lat": 48.1738045,
      "lng": 11.5562171,
      "neighborhood": "Olympiapark",
      "description": "An aquarium in the Olympic Park with tunnels, touch pools, sharks and rays. A compact, engaging outing for younger children.",
      "imageUrl": "assets/places/active-sea-life-munchen.jpg",
      "isPhoto": true
    },
    {
      "id": "active-botanischer-garten-munchen-nymphenburg",
      "category": "active",
      "name": "Botanischer Garten München-Nymphenburg",
      "rating": 4.7,
      "ratingCount": 9442,
      "address": "Nymphenburg, München",
      "lat": 48.1632652,
      "lng": 11.4998294,
      "neighborhood": "Nymphenburg",
      "description": "A magnificent botanical garden with glasshouses of palms, cacti and orchids plus outdoor themed gardens. Calm, colourful and stroller-friendly.",
      "imageUrl": "assets/places/active-botanischer-garten-munchen-nymphenburg.jpg",
      "isPhoto": true
    },
    {
      "id": "active-schyrenbad",
      "category": "active",
      "name": "Schyrenbad",
      "rating": 4.5,
      "ratingCount": 1191,
      "address": "Untergiesing, München",
      "lat": 48.11985,
      "lng": 11.5680725,
      "neighborhood": "Untergiesing",
      "description": "A charming outdoor summer pool by the Isar with lawns and diving boards. A refreshing family spot on a hot day.",
      "imageUrl": "assets/places/active-schyrenbad.jpg",
      "isPhoto": true
    },
    {
      "id": "active-sendlinger-tor-platz-to-marienplatz-stroll",
      "category": "active",
      "name": "Sendlinger-Tor-Platz to Marienplatz stroll",
      "rating": null,
      "ratingCount": null,
      "address": "Altstadt (Old Town), München",
      "lat": 48.1345,
      "lng": 11.568,
      "neighborhood": "Altstadt (Old Town)",
      "description": "The lively pedestrian route from Sendlinger Tor into the old town, lined with shops, buskers and the Asamkirche. An easy walk from the hotel.",
      "imageUrl": "assets/places/active-sendlinger-tor-platz-to-marienplatz-stroll.jpg",
      "isPhoto": true
    },
    {
      "id": "active-bavaria-filmstadt",
      "category": "active",
      "name": "Bavaria Filmstadt",
      "rating": 4.2,
      "ratingCount": 9402,
      "address": "Grünwald, München",
      "lat": 48.0654274,
      "lng": 11.554015,
      "neighborhood": "Grünwald",
      "description": "A film studio tour with sets, effects shows and a 4D cinema where kids can meet movie magic. A fun half-day adventure south of the city.",
      "imageUrl": "assets/places/active-bavaria-filmstadt.jpg",
      "isPhoto": true
    },
    {
      "id": "active-westbad",
      "category": "active",
      "name": "Westbad",
      "rating": 3.8,
      "ratingCount": 4530,
      "address": "Sendling-Westpark, München",
      "lat": 48.142231,
      "lng": 11.4754833,
      "neighborhood": "Sendling-Westpark",
      "description": "An indoor-outdoor pool complex with slides and family areas. A good bet for splashing whatever the weather.",
      "imageUrl": "assets/places/active-westbad.jpg",
      "isPhoto": true
    },
    {
      "id": "active-isarauen-at-reichenbachbrucke",
      "category": "active",
      "name": "Isarauen at Reichenbachbrücke",
      "rating": null,
      "ratingCount": null,
      "address": "Isarvorstadt, München",
      "lat": 48.129,
      "lng": 11.576,
      "neighborhood": "Isarvorstadt",
      "description": "Pebbly riverbanks and gentle Isar shallows perfect for paddling, stone-skipping and picnics, near the hotel. A lovely free outdoor escape.",
      "imageUrl": "assets/places/active-isarauen-at-reichenbachbrucke.jpg",
      "isPhoto": true
    },
    {
      "id": "active-skate-bike-bavariapark-loop",
      "category": "active",
      "name": "Skate & Bike Bavariapark loop",
      "rating": null,
      "ratingCount": null,
      "address": "Schwanthalerhöhe, München",
      "lat": 48.135,
      "lng": 11.542,
      "neighborhood": "Schwanthalerhöhe",
      "description": "Smooth wide paths around the park and exhibition grounds, great for scooters and bikes. Open space to burn off energy near the hotel.",
      "imageUrl": null,
      "isPhoto": false
    },
    {
      "id": "active-allianz-arena-tour",
      "category": "active",
      "name": "Allianz Arena (Tour)",
      "rating": 4.6,
      "ratingCount": 86185,
      "address": "Fröttmaning, München",
      "lat": 48.2187901,
      "lng": 11.6236227,
      "neighborhood": "Fröttmaning",
      "description": "The glowing home stadium of FC Bayern, with tours of the pitch, dugouts and museum. A thrill for young football fans.",
      "imageUrl": "assets/places/active-allianz-arena-tour.jpg",
      "isPhoto": true
    },
    {
      "id": "supermarket-rewe-city-hauptbahnhof",
      "category": "supermarket",
      "name": "REWE City Hauptbahnhof",
      "rating": null,
      "ratingCount": null,
      "address": "Ludwigsvorstadt, München",
      "lat": 48.1399279,
      "lng": 11.5616032,
      "neighborhood": "Ludwigsvorstadt",
      "description": "A large central-station supermarket with long hours for snacks, drinks and picnic supplies, near the hotel.",
      "imageUrl": "assets/defaults/supermarket.png",
      "isPhoto": false
    },
    {
      "id": "supermarket-edeka-schwanthalerstra-e",
      "category": "supermarket",
      "name": "EDEKA Schwanthalerstraße",
      "rating": null,
      "ratingCount": null,
      "address": "Ludwigsvorstadt, München",
      "lat": 48.1370723,
      "lng": 11.5482275,
      "neighborhood": "Schwanthalerhöhe",
      "description": "A well-stocked neighbourhood supermarket a couple of minutes from the hotel for groceries and fresh bread.",
      "imageUrl": "assets/defaults/supermarket.png",
      "isPhoto": false
    },
    {
      "id": "supermarket-aldi-sud-schwanthalerhohe",
      "category": "supermarket",
      "name": "ALDI SÜD Schwanthalerhöhe",
      "rating": null,
      "ratingCount": null,
      "address": "Schwanthalerhöhe, München",
      "lat": 48.133559,
      "lng": 11.545234,
      "neighborhood": "Schwanthalerhöhe",
      "description": "A no-frills discounter for cheap snacks and drinks, a short walk from the hotel toward Theresienwiese.",
      "imageUrl": "assets/defaults/supermarket.png",
      "isPhoto": false
    },
    {
      "id": "supermarket-vollcorner-biomarkt-isarvorstadt",
      "category": "supermarket",
      "name": "VollCorner Biomarkt Isarvorstadt",
      "rating": null,
      "ratingCount": null,
      "address": "Isarvorstadt, München",
      "lat": 48.1312,
      "lng": 11.568,
      "neighborhood": "Isarvorstadt",
      "description": "An organic supermarket with fresh produce, bread and wholefoods near Kapuzinerplatz, a short walk from the hotel.",
      "imageUrl": "assets/defaults/supermarket.png",
      "isPhoto": false
    },
    {
      "id": "supermarket-netto-schwanthalerstra-e",
      "category": "supermarket",
      "name": "Netto Schwanthalerstraße",
      "rating": null,
      "ratingCount": null,
      "address": "Ludwigsvorstadt, München",
      "lat": 48.1372992,
      "lng": 11.5600505,
      "neighborhood": "Ludwigsvorstadt",
      "description": "A discount supermarket close to the hotel for everyday basics at low prices.",
      "imageUrl": "assets/defaults/supermarket.png",
      "isPhoto": false
    },
    {
      "id": "supermarket-rewe-sendlinger-tor-platz",
      "category": "supermarket",
      "name": "REWE Sendlinger-Tor-Platz",
      "rating": null,
      "ratingCount": null,
      "address": "Altstadt (Old Town), München",
      "lat": 48.1347685,
      "lng": 11.5688959,
      "neighborhood": "Altstadt (Old Town)",
      "description": "A central supermarket at Sendlinger Tor, a few minutes' walk from the hotel, open late for essentials.",
      "imageUrl": "assets/defaults/supermarket.png",
      "isPhoto": false
    },
    {
      "id": "pharmacy-adler-apotheke-sonnenstra-e",
      "category": "pharmacy",
      "name": "Adler-Apotheke",
      "rating": 4.2,
      "ratingCount": 300,
      "address": "Ludwigsvorstadt, München",
      "lat": 48.1355355,
      "lng": 11.5717944,
      "neighborhood": "Altstadt (Old Town)",
      "description": "A central pharmacy near Sendlinger Tor with a wide range of medicines and toiletries.",
      "imageUrl": "assets/defaults/pharmacy.png",
      "isPhoto": false
    },
    {
      "id": "pharmacy-marien-apotheke-sendlinger-stra-e",
      "category": "pharmacy",
      "name": "Marien-Apotheke (Sendlinger Tor)",
      "rating": null,
      "ratingCount": null,
      "address": "Altstadt (Old Town), München",
      "lat": 48.1336954,
      "lng": 11.5652632,
      "neighborhood": "Altstadt (Old Town)",
      "description": "A long-standing pharmacy on the way into the old town, easy to reach from the hotel.",
      "imageUrl": "assets/defaults/pharmacy.png",
      "isPhoto": false
    },
    {
      "id": "pharmacy-isartor-apotheke",
      "category": "pharmacy",
      "name": "Isartor-Apotheke",
      "rating": 4,
      "ratingCount": 29,
      "address": "Altstadt (Old Town), München",
      "lat": 48.1339916,
      "lng": 11.5834122,
      "neighborhood": "Altstadt (Old Town)",
      "description": "A helpful pharmacy near the Isartor gate, handy while exploring the old town.",
      "imageUrl": "assets/defaults/pharmacy.png",
      "isPhoto": false
    },
    {
      "id": "pharmacy-theresien-apotheke",
      "category": "pharmacy",
      "name": "Theresien-Apotheke",
      "rating": null,
      "ratingCount": null,
      "address": "Ludwigsvorstadt, München",
      "lat": 48.1477479,
      "lng": 11.5766135,
      "neighborhood": "Maxvorstadt",
      "description": "A local pharmacy close to the Theresienwiese and the hotel for quick health essentials.",
      "imageUrl": "assets/defaults/pharmacy.png",
      "isPhoto": false
    }
  ]
};
